package com.melontubeproject_spring_boot.dto;

import java.util.ArrayList;
import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Music {
	
	private String singer;
	private String title;
	private String imageUrl;
	private String lyrics;
	
	public static List<Music> sampleMusic() {
		ArrayList<Music> list = new ArrayList<>();
		list.add(new Music("����", "That That", "https://cdnimg.melon.co.kr/cm2/album/images/109/37/474/10937474_20220428225312_500.jpg/melon/resize/120/quality/80/optimize", "20 22\r\n"
				+ "PSY Coming back (�̸� ���ʶ�)\r\n"
				+ "\r\n"
				+ "Long time no see huh?\r\n"
				+ "������������ huh?\r\n"
				+ "�츮 �ٽ� ���� ��� ������ ����\r\n"
				+ "Let��s get loco\r\n"
				+ "\r\n"
				+ "Pandemic's over uh\r\n"
				+ "�׷� ����� ���� uh\r\n"
				+ "�ٽ� �׺��� ���� uh\r\n"
				+ "Everybody say\r\n"
				+ "\r\n"
				+ "����������\r\n"
				+ "��½������\r\n"
				+ "�ò������Ÿ���\r\n"
				+ "�ʹ� ���� �����Ÿ���\r\n"
				+ "�������� Aye\r\n"
				+ "�������� Aye\r\n"
				+ "�� �� �� Throw yo hands in the air\r\n"
				+ "I say yeah\r\n"
				+ "\r\n"
				+ "Can you feel it?\r\n"
				+ "Can you feel it?\r\n"
				+ "Oh oh woo yeah Oh woo oh\r\n"
				+ "\r\n"
				+ "Can you feel it?\r\n"
				+ "Can you feel it?\r\n"
				+ "Oh oh woo yeah Ah\r\n"
				+ "\r\n"
				+ "�غ��Ͻð� (Go) ��� (Oh)\r\n"
				+ "That that I like that (Like that)\r\n"
				+ "��� ���� Babe (Babe)\r\n"
				+ "���� �� �� �� �Ʒ��� (Sing it)\r\n"
				+ "One two three to the four (Sing it)\r\n"
				+ "\r\n"
				+ "That that I like that\r\n"
				+ "That that I like that babe\r\n"
				+ "That that I like that\r\n"
				+ "It��s like that that yo\r\n"
				+ "\r\n"
				+ "That that I like that\r\n"
				+ "That that I like that babe\r\n"
				+ "That that I like that\r\n"
				+ "It��s like that\r\n"
				+ "\r\n"
				+ "�� ���� �� �ϴ� ������� ��Ծ���?\r\n"
				+ "That that I like that (Like that)\r\n"
				+ "�ð��� ������ ���Ծ���\r\n"
				+ "That that I like that (Like that)\r\n"
				+ "I don't care I don't care that I like that\r\n"
				+ "That that I like that (Like that)\r\n"
				+ "���� �ٶ󺸰� �ٶ�Դ� ������\r\n"
				+ "��� �� Ready set go\r\n"
				+ "�Ƿ� �þ ���� ������ ���� �����ϰ���\r\n"
				+ "�ʳ� �ٶ���� ���� �Ŷ� ��� ����\r\n"
				+ "������� ��ƴٰ� ������ ����\r\n"
				+ "������ �϶�� Oh oh oh\r\n"
				+ "�׳� ��ġ�� �� ���� ��ƺ��ڰ� Oh oh oh\r\n"
				+ "������� �����\r\n"
				+ "\r\n"
				+ "Can you feel it?\r\n"
				+ "Can you feel it?\r\n"
				+ "Oh oh woo yeah Oh woo oh\r\n"
				+ "\r\n"
				+ "Can you feel it?\r\n"
				+ "Can you feel it?\r\n"
				+ "Oh oh woo yeah Ah\r\n"
				+ "\r\n"
				+ "�غ��Ͻð� (Go) ��� (Oh)\r\n"
				+ "That that I like that (Like that)\r\n"
				+ "��� ���� Babe (Babe)\r\n"
				+ "���� �� �� �� �Ʒ��� (Sing it)\r\n"
				+ "One two three to the four (Sing it)\r\n"
				+ "\r\n"
				+ "That that I like that\r\n"
				+ "That that I like that babe\r\n"
				+ "That that I like that\r\n"
				+ "It��s like that that yo\r\n"
				+ "\r\n"
				+ "That that I like that\r\n"
				+ "That that I like that babe\r\n"
				+ "That that I like that\r\n"
				+ "It��s like that that yo\r\n"
				+ "\r\n"
				+ "Do what you wanna\r\n"
				+ "Say what you wanna\r\n"
				+ "Do what you wanna (Say what?)\r\n"
				+ "That that I like that babe\r\n"
				+ "\r\n"
				+ "Do what you wanna\r\n"
				+ "Say what you wanna\r\n"
				+ "Do what you wanna (Say what?)\r\n"
				+ "That that I like that babe\r\n"
				+ "That that I like that"));
		list.add(new Music("(����)���̵�", "TOMBOY", "https://cdnimg.melon.co.kr/cm2/album/images/108/90/384/10890384_20220314111504_500.jpg/melon/resize/120/quality/80/optimize", "Look at you �� �� ������ ��\r\n"
				+ "Ya took off hook\r\n"
				+ "����� Coke like brrr\r\n"
				+ "Look at my toe ���� Ex �̸� Tattoo\r\n"
				+ "I got to drink up now �װ� �ȴ� �ص� ����\r\n"
				+ "\r\n"
				+ "Why are you cranky, boy?\r\n"
				+ "�� �׸� ���׷� ��\r\n"
				+ "Do you want a blond barbie doll?\r\n"
				+ "It��s not here, I��m not a doll\r\n"
				+ "\r\n"
				+ "��ģ ���̶� ���� What��s the loss to me ya\r\n"
				+ "�������� ���� You��ll lose to me ya\r\n"
				+ "��� �ױ� �� ���� �� ���� ��ó �ϳ��� �����\r\n"
				+ "���� ���� �� ���� ����� �Ѹ� �ٿ�\r\n"
				+ "\r\n"
				+ "Ye I��m a Tomboy (Umm ah umm)\r\n"
				+ "Ye I��ll be the Tomboy (Umm ah)\r\n"
				+ "This is my attitude\r\n"
				+ "Ye I��ll be the Tomboy\r\n"
				+ "\r\n"
				+ "I don��t wanna play this ping pong\r\n"
				+ "I would rather film a Tik Tok\r\n"
				+ "Your mom raised you as a prince\r\n"
				+ "But this is queendom, right?\r\n"
				+ "I like dancing, I love ma friends\r\n"
				+ "Sometimes we swear without cigarettes\r\n"
				+ "I like to eh on drinking whiskey\r\n"
				+ "I won��t change it, what the hell?\r\n"
				+ "\r\n"
				+ "��ģ ô�̶� ���� What��s the loss to me ya\r\n"
				+ "�������� ������� You��re lost to me ya\r\n"
				+ "��� �ױ� �� ���� �� ���� ���� �� ��� �����\r\n"
				+ "���� ������ ���� �̼ҳ� ���� �ٿ�\r\n"
				+ "\r\n"
				+ "Ye I��m a Tomboy (Umm ah umm)\r\n"
				+ "Ye I��ll be the Tomboy (Umm ah)\r\n"
				+ "This is my attitude\r\n"
				+ "Ye I��ll be the Tomboy\r\n"
				+ "\r\n"
				+ "Said you get it?\r\n"
				+ "You get the song right, you��ll get what I mean ��Tomboy��"));
		list.add(new Music("IVE (���̺�)", "LOVE DIVE", "https://cdnimg.melon.co.kr/cm2/album/images/109/09/179/10909179_20220405103521_500.jpg/melon/resize/120/quality/80/optimize", "�װ� �� �ñ��� �װ� �ʵ� ��������\r\n"
				+ "�̰Ÿ� ����� �Ѱ� �Ѵ� �̷� ����\r\n"
				+ "���� �� ���� �̲����� ȣ���\r\n"
				+ "���� �ʿ� �� �ΰ� ���� �˰���\r\n"
				+ "\r\n"
				+ "Woo ������ �Ʒ���\r\n"
				+ "Woo ���߰� �ִ� ��\r\n"
				+ "Woo yeah It��s so bad It��s good\r\n"
				+ "�� �� ���� �� ���߰ھ�\r\n"
				+ "\r\n"
				+ "Narcissistic, my god I love it\r\n"
				+ "���θ� ���� ��\r\n"
				+ "�Ƹ��ٿ� � ���� �� ���� ����\r\n"
				+ "(�� ���Է� �� �װԷ�)\r\n"
				+ "�� ���� love dive\r\n"
				+ "\r\n"
				+ "Woo lalalalalalala\r\n"
				+ "Woo � �ͼ� love dive\r\n"
				+ "Woo oh perfect sacrifice yeah\r\n"
				+ "�� ���� love dive\r\n"
				+ "\r\n"
				+ "������ �̷��� �˴ٰ��� ����\r\n"
				+ "����̶�� �� �Ѽ����� �� �״�\r\n"
				+ "���� ���� �� ������ Ȯ����\r\n"
				+ "�� �� ���� ���� ���� ���� ��\r\n"
				+ "\r\n"
				+ "Woo ������ �ð���\r\n"
				+ "Woo 3�ʸ� �Ǵ� ��\r\n"
				+ "Woo yeah It��s so bad It��s good\r\n"
				+ "���ϸ� ���� �پ���\r\n"
				+ "\r\n"
				+ "Narcissistic, my god I love it\r\n"
				+ "���θ� ���� ��\r\n"
				+ "�Ƹ��ٿ� � ���� �� ���� ����\r\n"
				+ "(�� ���Է� �� �װԷ�)\r\n"
				+ "�� ���� love dive\r\n"
				+ "\r\n"
				+ "Woo lalalalalalala\r\n"
				+ "Woo � �ͼ� love dive\r\n"
				+ "Woo oh perfect sacrifice yeah\r\n"
				+ "�� ���� love dive\r\n"
				+ ""));
		list.add(new Music("��θ���", "����ΰ� ��", "https://cdnimg.melon.co.kr/cm2/album/images/108/71/162/10871162_20220217162422_500.jpg/melon/resize/120/quality/80/optimize", "�ʿ� �Բ� �ϰ� ���� �ϵ���\r\n"
				+ "����ϴ� ��\r\n"
				+ "���� �� �ϻ��� �ǰ�\r\n"
				+ "���� ��ſ��ϴ� ����� ���� ������\r\n"
				+ "�ڿ����� ���� ���� �ִ� ��\r\n"
				+ "���� �ൿ�� �������ϰ� ��ô�̴ٰ�\r\n"
				+ "������ ���� �������µ�\r\n"
				+ "�̰� ���� ���� ����� �ٵ�\r\n"
				+ "���� �Բ��� ���� �ٵ�\r\n"
				+ "�� ���Ƽ��� ���� ���� ��\r\n"
				+ "�ƹ����� ����ΰ� ��\r\n"
				+ "���� �ʿ� �ϰ� ���� �ϵ� �����ϸ鼭\r\n"
				+ "�Ϸ� ���� ���� �������µ�\r\n"
				+ "�̰� ���� ���� ����� �ٵ�\r\n"
				+ "���� �Բ��� ���� �ٵ�\r\n"
				+ "�� ���Ƽ��� ���� ���� ��\r\n"
				+ "�ƹ����� ����ΰ� ��\r\n"
				+ "���� �ູ���ϴ� ����� ���� ������\r\n"
				+ "���� �𸣰� ���� ���µ�\r\n"
				+ "�� ������ �˾��� �����ݾ�\r\n"
				+ "�ʵ� ��� ���� ���ݾ�\r\n"
				+ "���� �̷� �� �ƴ϶��\r\n"
				+ "�츮 ������ �����ݾ�\r\n"
				+ "�ƹ����� ����ΰ� ��"));
		list.add(new Music("BIGBANG (���)", "�����������ܿ� (Still Life)", "https://cdnimg.melon.co.kr/cm2/album/images/109/08/834/10908834_20220404174407_500.jpg/melon/resize/120/quality/80/optimize", "�̵��� �� �� �� �Ǵ� �� �ѿ��� ���� ��\r\n"
				+ "���� Ÿ �ܿ� ���� �� 1�� �� �� �Ǵٽ� ��\r\n"
				+ "\r\n"
				+ "������� �� ���� �� ������ �ȳ�\r\n"
				+ "�Ƹ���� �츮�� �� ���� ���� �ܿ�\r\n"
				+ "\r\n"
				+ "��Four seasons with no reason.��\r\n"
				+ "�� �� �ڿ� ���(����) ��� a happy end\r\n"
				+ "�񽺵��� �� ����� ĥ�� ������ ������\r\n"
				+ "ö���� ö ���� ö���� ����(still)\r\n"
				+ "ö������ ö �׸��� ����, Marchin�� ��ߵ�\r\n"
				+ "����������Ű, ������ ��踦 ������\r\n"
				+ "��ħ��, ��ġ ���� ����\r\n"
				+ "\r\n"
				+ "Boy �� �ϴø� �ٶ󺸰�\r\n"
				+ "����� �� ������ �־� Good-bye\r\n"
				+ "���� ��� �� ��Ÿ�� ���\r\n"
				+ "�Ӹ� �� ������\r\n"
				+ "�� ���� ������ amazon\r\n"
				+ "���� ���� Ʈ��츶 �� ����\r\n"
				+ "��� ���� �޷��� �� ��� �ϴ� �պ���\r\n"
				+ "���ҷ� �����ٴ� �����\r\n"
				+ "���� ��� �����\r\n"
				+ "�� ���� ��� �����\r\n"
				+ "��ħ �̽��� �°� �� �ȿ� �г� ���ſ� ����\r\n"
				+ "For Life\r\n"
				+ "\r\n"
				+ "����� ������ �ҳ�� �ҳడ �׸��� ��\r\n"
				+ "�����ߴ� ����ߴ� �� ������ �ڲ� ��ﳪ\r\n"
				+ "\r\n"
				+ "������ ���� ������ �������� �귯\r\n"
				+ "�Ӱ� �����̰� �Ķ��� �۵�� ������ �Ȱ�\r\n"
				+ "\r\n"
				+ "������ �ٽ� �� �׳� �׶��� ���Ͽ� (�״븦 ���Ͽ�)\r\n"
				+ "�Ƹ��ٿ� �츮�� �� ���� ���� �ܿ�\r\n"
				+ "\r\n"
				+ "La la la la la la la la la la la\r\n"
				+ "La la la la la la la la la la la\r\n"
				+ "La la la la la la la la la la la\r\n"
				+ "La la la la la la la la la la la\r\n"
				+ "\r\n"
				+ "�̵��� �� �� �� �Ǵ� �� �ѿ��� ���� ��\r\n"
				+ "���� Ÿ �ܿ� ���� �� �� ���� ���� �ܿ�"));
		list.add(new Music("�ӿ���", "����� �� ������", "https://cdnimg.melon.co.kr/cm2/album/images/107/35/654/10735654_20211008114339_500.jpg/melon/resize/120/quality/80/optimize", "������ ���� �� ���� ������\r\n"
				+ "�� ��� �ձ��� �ڲ� ������ ����\r\n"
				+ "������ ���ϰ� ������ ������\r\n"
				+ "�� �Ƹ���� �����\r\n"
				+ "����̶� �� �� ���� �Ŵ���\r\n"
				+ "������ �Ҽ��� �� �־�������\r\n"
				+ "�̺��̶� �� �� ���� �Ŵ���\r\n"
				+ "�� ���� ���� �����\r\n"
				+ "����� �� ������\r\n"
				+ "������ ����ó��\r\n"
				+ "�࿩ ���ƹ����� ��\r\n"
				+ "�� ����������\r\n"
				+ "�׸����� �Ѿ� ����� �� ������\r\n"
				+ "��� ����� ���� �ٵ�\r\n"
				+ "�ٶ��� �д� �ʱ��� ������\r\n"
				+ "������ �̺��� ������ ���ö�\r\n"
				+ "���� ���ؼ� ������ �繫ģ\r\n"
				+ "�� �����ߴ� �����\r\n"
				+ "����� �� ������\r\n"
				+ "������ ����ó��\r\n"
				+ "�࿩ ���ƹ����� ��\r\n"
				+ "�� ����������\r\n"
				+ "�׸����� �Ѿ� ����� �� ������\r\n"
				+ "��� ����� ���� �ٵ�\r\n"
				+ "��ٸ��� ���¿� �� ������ �ϴµ�\r\n"
				+ "���� ã�� �� ���� �����ϱ�\r\n"
				+ "���� ã�� ���� �ֳ�\r\n"
				+ "����� �� ������\r\n"
				+ "������ ����ó��\r\n"
				+ "�࿩ ���ƹ����� ��\r\n"
				+ "�� ����������\r\n"
				+ "�׸����� �Ѿ� ����� �� ������\r\n"
				+ "��� ����� ���� �ٵ�\r\n"
				+ "��� ����� ���� �ٵ�"));
		list.add(new Music("BIG Naughty (������)", "���̶�� ���� (Feat. 10CM)", "https://cdnimg.melon.co.kr/cm2/album/images/109/25/762/10925762_20220419152007_500.jpg/melon/resize/120/quality/80/optimize", "Back to the day\r\n"
				+ "�� 10�밡 ���� ��\r\n"
				+ "�׶� ���� �� ���� ���ߴٸ�\r\n"
				+ "����� ��\r\n"
				+ "������ �ܷο����� �㿡 You say\r\n"
				+ "�帰 �߾� �ӿ� �װ� �Ȱ� ����\r\n"
				+ "Yeah ģ������� ���ڸ�\r\n"
				+ "���� �� �� ��⸦ ����\r\n"
				+ "���� �ʹٴ� �̵θ���\r\n"
				+ "ģ���� ���� ����\r\n"
				+ "10�⵵ �� �� �ָ� ����� �� �ֆv\r\n"
				+ "���� �׸� ������\r\n"
				+ "�ٵ� �װ� �� �ȵ�\r\n"
				+ "�׷� �� ��������\r\n"
				+ "�� �ƴ��� ����� ����\r\n"
				+ "But �� ���� �� �����ϱ�\r\n"
				+ "�� ��ȭ �ٷ� �Ⱦ�\r\n"
				+ "���� �ּ� ���\r\n"
				+ "���� ������� �� �� �״ϱ�\r\n"
				+ "�װ� ����� �Ƴ�\r\n"
				+ "�װ� �̷��� �Ƴ�\r\n"
				+ "�׳� ���̶�� ����\r\n"
				+ "�Ӹ� �װ� �� �˾�\r\n"
				+ "�̰� ����� �¾�\r\n"
				+ "�и� ����ߴ� ���̾�\r\n"
				+ "I know I��m wrong\r\n"
				+ "�� �ڸ��� �״��\r\n"
				+ "�ΰ� �� ������\r\n"
				+ "����� ���� ����"));
		list.add(new Music("�ӿ���", "�츮���� ��罺", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "������ ���ƿ� �Բ� �ߴ� ����\r\n"
				+ "������ �� ����\r\n"
				+ "�״� �ڸ� ���ƺ��� �ſ�\r\n"
				+ "������ ���ƿ� ������ ������\r\n"
				+ "���� ���� �� ������ �״뿡��\r\n"
				+ "���� �翡 �����Կ�\r\n"
				+ "�״� ���� �뷡�ҰԿ�\r\n"
				+ "���� ���ƿ�\r\n"
				+ "�״� ���� ����ҰԿ�\r\n"
				+ "������ �츮 �ð� ������\r\n"
				+ "�˰� �ǰ���\r\n"
				+ "�׶� ���� �� ���� �� ����ҰԿ�\r\n"
				+ "�׶� �̼� ������\r\n"
				+ "���� �ູ���� ���\r\n"
				+ "�ܷӰ� ��ĥ �� ����� �ٰԿ�\r\n"
				+ "������ £���� ���� ������ ��\r\n"
				+ "�� �� ����� �ɰԿ�\r\n"
				+ "�״� �ε� ���� ���ƿ�\r\n"
				+ "���� ���ƿ�\r\n"
				+ "�״뿡�� ���� �ɰԿ�\r\n"
				+ "������ �츮 �ð� ������\r\n"
				+ "�˰� �ǰ���\r\n"
				+ "�׶� ���� �� ���� �� ����ҰԿ�\r\n"
				+ "��ǳ �ӿ� ȥ�� ���� ��ŵ� ��\r\n"
				+ "���� �Ǿ� ��ų�Կ� �״�\r\n"
				+ "�״� ���� �뷡�ҰԿ�\r\n"
				+ "���� ���ƿ�\r\n"
				+ "�״� ���� ����ҰԿ�\r\n"
				+ "��ο� ���� ��� ���ߴ�\r\n"
				+ "�״��� ���� �ɰԿ�"));
		list.add(new Music("�漭", "���� X����", "https://cdnimg.melon.co.kr/cm2/album/images/109/29/486/10929486_20220422151852_500.jpg/melon/resize/120/quality/80/optimize", "�츮 �ٽ� ������\r\n"
				+ "���ڰ� ������\r\n"
				+ "��� �߾����\r\n"
				+ "�ʹ� �׸���\r\n"
				+ "���� ǰ�� �ȱ淡\r\n"
				+ "�� ���� ������\r\n"
				+ "�װ� ���� �ž�\r\n"
				+ "�ʸ� �����Ѵٰ�\r\n"
				+ "�ȳ� �״��\r\n"
				+ "���� ��� ����\r\n"
				+ "���μ��� �ȴٰ�\r\n"
				+ "������ ����\r\n"
				+ "�ູ�� ���̴� ����� �ӿ�\r\n"
				+ "�츮 �Ѹ� ���\r\n"
				+ "����߾���\r\n"
				+ "�� ���� �� ��\r\n"
				+ "�׻� �ڵ��ƺ���\r\n"
				+ "�� ���� �����ִ�\r\n"
				+ "�װ� ��������\r\n"
				+ "�츮 �ٽ� ������\r\n"
				+ "���ڰ� ������\r\n"
				+ "��� �߾����\r\n"
				+ "�ʹ� �׸���\r\n"
				+ "���� ǰ�� �ȱ淡\r\n"
				+ "�� ���� ������\r\n"
				+ "�װ� ���� �ž�\r\n"
				+ "�ʸ� �����Ѵٰ�\r\n"
				+ "����ϸ��� ����\r\n"
				+ "�Ѱ�������\r\n"
				+ "�̾��� �ϳ���\r\n"
				+ "��������\r\n"
				+ "���ɿ������� ��� ������\r\n"
				+ "�η��� �� ������\r\n"
				+ "�ʸ� ������\r\n"
				+ "�� ����� ��\r\n"
				+ "���� �ʹ� �׸���\r\n"
				+ "�� ���� �����ִ�\r\n"
				+ "�װ� ���� �;�\r\n"
				+ "�츮 �ٽ� ������\r\n"
				+ "���ڰ� ������\r\n"
				+ "��� �߾����\r\n"
				+ "�ʹ� �׸���\r\n"
				+ "���� ǰ�� �ȱ淡\r\n"
				+ "�� ���� ������\r\n"
				+ "�װ� ���� �ž�\r\n"
				+ "�ʸ� �����Ѵٰ�\r\n"
				+ "���� �� ���� ����\r\n"
				+ "�� �ٽ� ������\r\n"
				+ "�� ���� ��뼭\r\n"
				+ "���� �;�\r\n"
				+ "���� ǰ�� �ȱ淡\r\n"
				+ "�� ���� ������\r\n"
				+ "�� �翡 �־���\r\n"
				+ "���� �ʻ��̶��"));
		list.add(new Music("LE SSERAFIM (��������)", "FEARLESS", "https://cdnimg.melon.co.kr/cm2/album/images/109/39/458/10939458_20220502123814_500.jpg/melon/resize/120/quality/80/optimize", "Bam ba ba ba ba bam ba ba ba ba bam\r\n"
				+ "Ba ba ba ba bam\r\n"
				+ "Bam ba ba ba ba bam ba ba ba ba bam\r\n"
				+ "Ba ba ba ba bam\r\n"
				+ "\r\n"
				+ "���� ���� ���� �� ��� ���� ������ �� answer\r\n"
				+ "�� ���� �ӿ� ���ٴ� new wave �� �Ŵ��� passion\r\n"
				+ "���� ���� ���ſ� ��ΰ� �˰� �ִ� �� Ʈ���� huh\r\n"
				+ "I'm fearless a new b**ch new crazy �ö� next one\r\n"
				+ "\r\n"
				+ "����� highway highway\r\n"
				+ "���� �ḻ�� ���\r\n"
				+ "�� ������ ���� �Ϻζ��\r\n"
				+ "���� �� ���� ����\r\n"
				+ "\r\n"
				+ "What you lookin�� at\r\n"
				+ "What you what you lookin�� at\r\n"
				+ "What you lookin�� at\r\n"
				+ "What you what you lookin�� at\r\n"
				+ "What you lookin�� at\r\n"
				+ "What you what you lookin�� at\r\n"
				+ "Mmmm I��m fearless huh\r\n"
				+ "\r\n"
				+ "You should get away\r\n"
				+ "Get a get a get away\r\n"
				+ "��ġ�� �ʰ� ��ġ ��ġ�� �ʰ�\r\n"
				+ "You should get away\r\n"
				+ "Get a get a get away\r\n"
				+ "Mmmm I��m fearless huh\r\n"
				+ "\r\n"
				+ "Bam ba ba ba ba bam ba ba ba ba bam\r\n"
				+ "Ba ba ba ba bam\r\n"
				+ "Bam ba ba ba ba bam ba ba ba ba bam\r\n"
				+ "Ba ba ba ba bam\r\n"
				+ "\r\n"
				+ "����� ������ �� ������ �̻���\r\n"
				+ "����� ���� ���� �� �� �̻� �� ��\r\n"
				+ "������ forever win ���� ay\r\n"
				+ "�����ſ� ���� 1 ���� ay\r\n"
				+ "�� ������ ���Ƹ� ���� ay\r\n"
				+ "Take the world break it down break you down down\r\n"
				+ "\r\n"
				+ "����� highway highway\r\n"
				+ "���� �ḻ�� ���\r\n"
				+ "�� ������ ���� �Ϻζ��\r\n"
				+ "���� �� ���� ����\r\n"
				+ ""));
		list.add(new Music("�ӿ���", "�ٽ� ���� �� ������", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "�ʸ� ���� �� �� ���� �ϳ� ���\r\n"
				+ "���� ���ۿ� ������\r\n"
				+ "�װ� ���� ��� ���� ���� ���ؼ�\r\n"
				+ "���������� �����\r\n"
				+ "��ȸ�� ������ �Ѽ� �ڶ���\r\n"
				+ "�ø� �ٶ�ó��\r\n"
				+ "���� ġ�� �� �� ������\r\n"
				+ "�츮 ���� �� ������\r\n"
				+ "�ٽ� ���� �� ������\r\n"
				+ "�׸� ���� ����ó�� �׶�ó��\r\n"
				+ "�ǵ��ư� �� ������\r\n"
				+ "�ٽ� �츮�� ������\r\n"
				+ "������ �ؾ߸� �ұ�\r\n"
				+ "���θ� ǰ�� �Ȱ�\r\n"
				+ "�Ͽ����� ������ �������\r\n"
				+ "������ �����̾� �����ڳĸ���\r\n"
				+ "�׶� �� �β�������\r\n"
				+ "�����ϰ� �Ͼ �� �ٽ� ã�ư�\r\n"
				+ "�߰ſ� �޸� �پ���\r\n"
				+ "���� �Բ� �ߴ� ����������\r\n"
				+ "�ø� ����ó��\r\n"
				+ "������� �� �� ������\r\n"
				+ "�츮 ���� �� ������\r\n"
				+ "�ٽ� ���� �� ������\r\n"
				+ "�׸� ���� ����ó�� �׶�ó��\r\n"
				+ "�ǵ��ư� �� ������\r\n"
				+ "�ٽ� �츮�� ������\r\n"
				+ "������ �ؾ߸� �ұ�\r\n"
				+ "���θ� ǰ�� �Ȱ�\r\n"
				+ "�Ͽ����� ������ �������\r\n"
				+ "�׸��� ������ ������ �귯����\r\n"
				+ "�ʿ��� ���� ��\r\n"
				+ "�츮 ���� �� ������\r\n"
				+ "�ٽ� ���� �� ������\r\n"
				+ "�׸� ���� ����ó�� �׶�ó��\r\n"
				+ "�ǵ��ư� �� ������\r\n"
				+ "�ٽ� �츮�� ������\r\n"
				+ "������ �ؾ߸� �ұ�\r\n"
				+ "���θ� ǰ�� �Ȱ�\r\n"
				+ "�Ͽ����� ������ �������"));
		list.add(new Music("BE'O (���)", "LOVE me", "https://cdnimg.melon.co.kr/cm2/album/images/109/16/904/10916904_20220412101049_500.jpg/melon/resize/120/quality/80/optimize", "Hey girl, Where you at? (Where you at?)\r\n"
				+ "��ü ��� �� �ϴ��� �ñ���\r\n"
				+ "����� �ʹ� Bad Bad (So bad)\r\n"
				+ "ħ�밡 ������ ���� �� ���ݾ�\r\n"
				+ "\r\n"
				+ "��̵� ���� TV show\r\n"
				+ "�� ������ ��� Pretty boy\r\n"
				+ "�� ����� ���� �о����\r\n"
				+ "���� ǥ���� ���� ������\r\n"
				+ "\r\n"
				+ "���Ŀ� �� �� ��Ⱑ ����\r\n"
				+ "�� ���� �ڲ� ���� ���� Yeah\r\n"
				+ "�̸� �˾Ƶ� �� �̸�\r\n"
				+ "��û�ϰ� �ൿ�� �ع����ٴϱ�\r\n"
				+ "\r\n"
				+ "Oh please\r\n"
				+ "Love me love me love me\r\n"
				+ "I know, I'm stupid\r\n"
				+ "��¿ �� ���� �� ���� ������\r\n"
				+ "\r\n"
				+ "Oh please\r\n"
				+ "Love me love me love me\r\n"
				+ "I know, I'm stupid\r\n"
				+ "��¿ �� ���� �� ���� ������\r\n"
				+ "\r\n"
				+ "Now I say I love you\r\n"
				+ "So I love you\r\n"
				+ "Now I say I love you\r\n"
				+ "�� �������� ����\r\n"
				+ "\r\n"
				+ "Now I say I love you\r\n"
				+ "So I love you\r\n"
				+ "Now I say I love you\r\n"
				+ "�� �������� ����\r\n"
				+ "\r\n"
				+ "Oh please\r\n"
				+ "Love me love me love me\r\n"
				+ "I know, I'm stupid\r\n"
				+ "��¿ �� ���� �� ���� ������\r\n"
				+ "\r\n"
				+ "Oh please\r\n"
				+ "Love me love me love me\r\n"
				+ "I know, I'm stupid\r\n"
				+ "��¿ �� ���� �� ���� ������\r\n"
				+ "Now I say I love you"));
		list.add(new Music("Red Velvet (���座��)", "Feel My Rhythm", "https://cdnimg.melon.co.kr/cm2/album/images/108/94/554/10894554_20220321100622_500.jpg/melon/resize/120/quality/80/optimize", "Red Velvet\r\n"
				+ "\r\n"
				+ "����ȸ�� ������\r\n"
				+ "���� �Ҷ��� �� ������\r\n"
				+ "This is gonna be a crazy night\r\n"
				+ "(To-na-na-na-na-na-night)\r\n"
				+ "\r\n"
				+ "������� �λ���� �İ����̰�\r\n"
				+ "�츮 ��¦ ��ƺ���\r\n"
				+ "�����ϰ� Bae bae\r\n"
				+ "���ݺ��� ������ ����\r\n"
				+ "(Feel my vibe and sway)\r\n"
				+ "\r\n"
				+ "�ɰ��縦 ����\r\n"
				+ "������ �� ũ�� ��Ʈ��\r\n"
				+ "�츱 ������ ��߿� ������ ��\r\n"
				+ "�����ο� ����\r\n"
				+ "\r\n"
				+ "Feel my rhythm Come with me\r\n"
				+ "����� �� ������\r\n"
				+ "�뷡�� ���� �� �޺��� ���� ��\r\n"
				+ "�ٷ� ���� (Play my rhythm)\r\n"
				+ "\r\n"
				+ "Follow follow my heartbeat\r\n"
				+ "�ذ� ���� ������\r\n"
				+ "Feel my rhythm ������ ���� ��\r\n"
				+ "�� ������ ���� �� Baby\r\n"
				+ "\r\n"
				+ "���� Old and Classic\r\n"
				+ "(Just ride)\r\n"
				+ "���� ���� ���� �ٸ� ��������\r\n"
				+ "(Get loud)\r\n"
				+ "����� �� ���� �� �ð� ��\r\n"
				+ "���� ���� ������\r\n"
				+ "�� ���� ������ �츰\r\n"
				+ "Fun and wild and brave\r\n"
				+ "\r\n"
				+ "�ü��� ���� �� Motion\r\n"
				+ "G-give me a new direction\r\n"
				+ "������ Black holeó��\r\n"
				+ "������� Sweet emotion\r\n"
				+ "�ʸ� �¿� ä (Sway)\r\n"
				+ "���ε� ������ (Way)\r\n"
				+ "�� ���� ��� ��踦\r\n"
				+ "�� �������� (Oh yeah)\r\n"
				+ "\r\n"
				+ "�ɰ��縦 ����\r\n"
				+ "(�𳯷�)\r\n"
				+ "Champagne�� �� ũ�� ��Ʈ��\r\n"
				+ "(������)\r\n"
				+ "���� ������ ���Ͽ� ������ ��\r\n"
				+ "�����ο� ����"));
		list.add(new Music("��μ� (��θ���)", "���߰��", "https://cdnimg.melon.co.kr/cm2/album/images/108/16/959/10816959_20211217144957_500.jpg/melon/resize/120/quality/80/optimize", "���ϰ� �־��� �ʾ�����\r\n"
				+ "��� ���÷�\r\n"
				+ "���� �� ��� �ִ�\r\n"
				+ "�����Ϳ� �ɾ� �־�\r\n"
				+ "ģ���� ������ ��������\r\n"
				+ "���� �� �ߴµ�\r\n"
				+ "�ڲٸ� �� �� ���ö�\r\n"
				+ "������ �޷��Ծ�\r\n"
				+ "�� �� �𸣰ڴ�\r\n"
				+ "���� �� ��ģ ���ó��\r\n"
				+ "�ʸ� ������\r\n"
				+ "��å���� �װ� ���� ������\r\n"
				+ "�Ƴ� �� ���߾� ��¥��\r\n"
				+ "�� ���� �����\r\n"
				+ "������ ����ŭ ���ϰ� �־�\r\n"
				+ "������ ������\r\n"
				+ "���� ��ȭ�� �峭ġ��\r\n"
				+ "�ָ��� ���Ұųĸ�\r\n"
				+ "���� ���� ���� ����\r\n"
				+ "�׸��� �ѹ��� ���� �ַ� ��µ�\r\n"
				+ "�� �׳� �شٰ�\r\n"
				+ "���� �� ������ �� ������ ��ž�\r\n"
				+ "�� �� �𸣰ڴ�\r\n"
				+ "���� �� ��ģ ���ó��\r\n"
				+ "�ʸ� ������\r\n"
				+ "��å���� �װ� ���� ������\r\n"
				+ "�Ƴ� �� ���߾� ��¥��\r\n"
				+ "�� ���� �����\r\n"
				+ "�����̾� �Ͼ���\r\n"
				+ "���ڱ� �̷� �� ����ٸ� �̾���\r\n"
				+ "�δ��� �Ǵ°� �翬��\r\n"
				+ "������ ��\r\n"
				+ "������ �� ��鵵 ������ �ְڴ� oh\r\n"
				+ "���� ���� ���������\r\n"
				+ "���� �����ϸ� ��;��ٷ�\r\n"
				+ "��ȸ���� �� ���ְ� ������\r\n"
				+ "�� �Ŀ��� �ϰ� �ȴٸ�\r\n"
				+ "�� �׶� �����Ұ�\r\n"
				+ "������ ���Ұ� ȥ�� ���ð�\r\n"
				+ "�����̾� �ʸ� ����ϰ� �־�"));
		list.add(new Music("�����", "GANADARA (Feat. ������)", "https://cdnimg.melon.co.kr/cm2/album/images/108/89/981/10889981_20220311110820_500.jpg/melon/resize/120/quality/80/optimize", "��Ÿ��� �ȴ� ����\r\n"
				+ "��� �뷡�� �귯����\r\n"
				+ "���� �� ���� �� ������\r\n"
				+ "�� �ѱ������� ������\r\n"
				+ "�����⵵ ���� ���� �� ��\r\n"
				+ "�� ���� ��� ������\r\n"
				+ "� �ܾ ���� I don��t know\r\n"
				+ "� ���� ���� I don��t know\r\n"
				+ "���� �� �̷��� I don��t know\r\n"
				+ "You��re on my mind\r\n"
				+ "� �ܾ ���� I don��t know\r\n"
				+ "� ���� ���� I don��t know\r\n"
				+ "���� �� �̷��� I don��t know\r\n"
				+ "You��re on my mind\r\n"
				+ "Baby ���� ���� �� ��\r\n"
				+ "Body language�� �ڽ� �־�\r\n"
				+ "�����ٰ�\r\n"
				+ "girl just give me some your time\r\n"
				+ "�ʸ� ���� �տ� �� ��\r\n"
				+ "���� Ǯ�� �� �� ������\r\n"
				+ "Let me take u on a magic carpet ride\r\n"
				+ "���� ��� �����\r\n"
				+ "���� ���� ������\r\n"
				+ "�������� ���� ��\r\n"
				+ "�����ٶ󸶹ٻ�\r\n"
				+ "���� ��� �����\r\n"
				+ "���� ���� ������\r\n"
				+ "�������� ���� ��\r\n"
				+ "�����ٶ󸶹ٻ�\r\n"
				+ "�ʹ� �Ϻ����� �ʾƵ�\r\n"
				+ "���� �� �� ���� ���� �� �� ����\r\n"
				+ "�װ� �� �� �ٰ��� ����\r\n"
				+ "����� ���� ��\r\n"
				+ "��Ÿ��� �ȴ� ����\r\n"
				+ "��� ��� �� ������ ��\r\n"
				+ "�̷� �� ����� �� ������\r\n"
				+ "������ ������\r\n"
				+ "��Ŵ� �� �հ�������\r\n"
				+ "�ڲٸ� ������ ���� ��\r\n"
				+ "Body language�� ���� ������\r\n"
				+ "But ���� �� ���� �׳� ������\r\n"
				+ "��� ���� �˷��ٰ� ���� ��\r\n"
				+ "���� ���� ����ó�� ������\r\n"
				+ "�ʸ� �� ���� ���� ������\r\n"
				+ "I wouldn��t mind if I died in your arms\r\n"
				+ "���� ��� �����\r\n"
				+ "���� ���� ������\r\n"
				+ "�������� ���� ��\r\n"
				+ "�����ٶ󸶹ٻ�\r\n"
				+ "���� ��� �����\r\n"
				+ "���� ���� ������\r\n"
				+ "�������� ���� ��\r\n"
				+ "�����ٶ󸶹ٻ�\r\n"
				+ "���� ��� �����\r\n"
				+ "���� ���� ������\r\n"
				+ "�������� ���� ��\r\n"
				+ "�����ٶ󸶹ٻ�\r\n"
				+ "���� ��� �����\r\n"
				+ "���� ���� ������\r\n"
				+ "�������� ���� ��\r\n"
				+ "�����ٶ󸶹ٻ�"));
		list.add(new Music("�ӿ���", "���� ���� �Ͼ��", "https://cdnimg.melon.co.kr/cm2/album/images/104/12/319/10412319_20200403103006_500.jpg/melon/resize/120/quality/80/optimize", "���� ���� �ɱ� �����ߴ� ���Լ�\r\n"
				+ "������ �� �ϴ� ���� ���� �ӹ� ���\r\n"
				+ "���� �ô� �ɱ� ���� �͵� ���� ����\r\n"
				+ "������ �� ���� ��� �� �̲� ���\r\n"
				+ "�ְ���\r\n"
				+ "�״� �� �ӿ� ��ģ �� ���\r\n"
				+ "������ ���Լ� �״� �����ٰ�\r\n"
				+ "���� �� ����\r\n"
				+ "���� ���� ū �״� ����� �ɰ�\r\n"
				+ "�״� ���� �ɾ��\r\n"
				+ "�ȴٰ� ��ġ��\r\n"
				+ "���� �״븦 �Ȱ� ���� ����\r\n"
				+ "���� ���� �Ͼ��\r\n"
				+ "���� �ΰ� ����\r\n"
				+ "���� ���� �� ����� ��\r\n"
				+ "�״밡 �Ǿ ���� ���� �ž�\r\n"
				+ "���� �� ����\r\n"
				+ "���� ���� ū �״� ����� �ɰ�\r\n"
				+ "�״� ���� �ɾ��\r\n"
				+ "�ȴٰ� ��ġ��\r\n"
				+ "���� �״븦 �Ȱ� ���� ����\r\n"
				+ "���� ���� �Ͼ��\r\n"
				+ "���� ������ ���ΰ��� �Ǿ�\r\n"
				+ "�ٽ� ���� �տ�����\r\n"
				+ "�״�� �� ������ ����\r\n"
				+ "���� ���� ���ߴ� Ȧ�� ����ߴ� �ð�\r\n"
				+ "���� �̾��ؿ� ����ؿ�\r\n"
				+ "�� ������\r\n"
				+ "�츮�� �ΰ� ���� �峭�� �߰�\r\n"
				+ "�츰 ���� ���� �ž�\r\n"
				+ "���� ���� ����\r\n"
				+ "���� �� ������� ���� �����\r\n"
				+ "���� �״� ���ϱ�\r\n"
				+ "�״�� ���� ���ƿ�\r\n"
				+ "���� ���� �Ͼ��"));
		list.add(new Music("�ӿ���", "������", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "���� �Ϸ� �������\r\n"
				+ "���� ���������\r\n"
				+ "���� �ʰ� �޷��Դ� �濡��\r\n"
				+ "���� �Բ� �����\r\n"
				+ "�׳� �ƹ��� �غ� ����\r\n"
				+ "���������\r\n"
				+ "����ص� �����ϱ�\r\n"
				+ "�츮 �Բ� ����\r\n"
				+ "Du Du Du Du Du\r\n"
				+ "�ູ ���� ���� �賶 �ϳ� �ް�\r\n"
				+ "����ߴ� �ϻ�� ������ ���\r\n"
				+ "Du Du Du Du\r\n"
				+ "Du Du Du Du\r\n"
				+ "����������\r\n"
				+ "���� ��� ���� ������\r\n"
				+ "��Ŭ���� �Ӹ���\r\n"
				+ "�����ٸ� �״� �Ⱦ��� ���\r\n"
				+ "�ٷ� �״� �翡 ����\r\n"
				+ "� ���۶� �ϳ� ì�ܼ�\r\n"
				+ "���������\r\n"
				+ "����ص� �����ϱ�\r\n"
				+ "�츮 �Բ� ����\r\n"
				+ "Du Du Du Du Du\r\n"
				+ "�ູ ���� ���� �賶 �ϳ� �ް�\r\n"
				+ "����ߴ� �ϻ�� ������ ���\r\n"
				+ "Du Du Du Du\r\n"
				+ "Du Du Du Du\r\n"
				+ "����������\r\n"
				+ "�츮 �Բ� ����\r\n"
				+ "Du Du Du Du Du\r\n"
				+ "�ູ ���� ���� �賶 �ϳ� �ް�\r\n"
				+ "����ߴ� �ϻ�� ������ ���\r\n"
				+ "Du Du Du Du\r\n"
				+ "Du Du Du Du\r\n"
				+ "����������\r\n"
				+ "�츮 �Բ� ����\r\n"
				+ "Du Du Du Du Du\r\n"
				+ "Du Du Du Du\r\n"
				+ "Du Du Du Du\r\n"
				+ "����������\r\n"
				+ "Du Du Du Du\r\n"
				+ "Du Du Du Du\r\n"
				+ "����������\r\n"
				+ "Du Du Du Du\r\n"
				+ "Du Du Du Du\r\n"
				+ "���� ������"));
		list.add(new Music("����ƾ", "HOT", "https://cdnimg.melon.co.kr/cm2/album/images/109/22/231/10922231_20220527120653_500.jpg/melon/resize/120/quality/80/optimize", "��� �츱 �Ĵٺ� (��)\r\n"
				+ "�¾� ���� �޸��� ���� (��� �޷� Uh)\r\n"
				+ "Juicy Juicy Juicy Juicy\r\n"
				+ "\r\n"
				+ "�Ѽ��� ��� ���� ���� (Spicy�� Feelin��)\r\n"
				+ "�¾��� �������� �� (I just wanna do this)\r\n"
				+ "Juicy Juicy\r\n"
				+ "\r\n"
				+ "���� �Ҹ� ũ�� Turn up\r\n"
				+ "������ �������� �޷�\r\n"
				+ "�¾��� �ڿ� �ް� ��� ���� ��� �츮��� Fire (�츮���)\r\n"
				+ "\r\n"
				+ "�� ���󰡷� �� (�� ���󰡷� ��)\r\n"
				+ "�츮 ��Ĵ�� �� �� (�츮 ��Ĵ�� �� ��)\r\n"
				+ "Say ah �߰ſ� �߰ſ� �߰ſ�\r\n"
				+ "\r\n"
				+ "���� ���� �� �ϴ��� ������\r\n"
				+ "��� ���� ���� �ϳ��� ���� (�ϳ� �� ����)\r\n"
				+ "���� ��ȣ��� ���� ���� Vibe\r\n"
				+ "����� �¾翡 ������ �ɾ��\r\n"
				+ "������� Go\r\n"
				+ "\r\n"
				+ "�츮�� Drop it like HOT HOT HOT (Oh ���� Feelin�� so HOT)\r\n"
				+ "�� �뷡 Burnin�� like HOT HOT HOT HOT (Boom Brr Boom Boom)\r\n"
				+ "�츮�� Drop it like HOT HOT HOT (Oh ���� Feelin�� so HOT)\r\n"
				+ "Yeah I��m runnin�� too HOT HOT HOT HOT (Boom Brr Boom Boom)\r\n"
				+ "\r\n"
				+ "�¾��� ���� �Һٿ���\r\n"
				+ "���� �̰߰� (Boom Brr Boom Boom)\r\n"
				+ "�¾��� ���� �Һٿ���\r\n"
				+ "�߰ſ� �� �뷡 Everybody ��â\r\n"
				+ "\r\n"
				+ "Ay ������ �Ҿ�� �縷�� �ĵ� ���̷� Drive away\r\n"
				+ "I don��t want uh one more chance\r\n"
				+ "�� ������ ��� �� ������\r\n"
				+ ""));
		list.add(new Music("�ӿ���", "�ƹ���", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "�Ͼ� �Ӹ� �̾� �޶��\r\n"
				+ "�� �� �� ���̶��\r\n"
				+ "�� ���� �� ��������\r\n"
				+ "���� �� ���� ���ҳ�\r\n"
				+ "�׷��Ե� ���� ��ĸ�\r\n"
				+ "���� �����Ͻô�\r\n"
				+ "����� �������\r\n"
				+ "�ָ��� ���� �� �ƹ���\r\n"
				+ "������ �ƹ��� ����\r\n"
				+ "��� ������ �ߵ� �� ����\r\n"
				+ "�������� �� ��Ű��\r\n"
				+ "�׳� �翡�� �־� �ּ���\r\n"
				+ "Ȱ¦ ���� ����� ��� ���� ������\r\n"
				+ "������ ���� �� �ϴ� ���\r\n"
				+ "������ ���� �����ٰ�\r\n"
				+ "����̷� ���ư� ����\r\n"
				+ "����ϴ� �� �ƹ���\r\n"
				+ "�������� �� ��Ű��\r\n"
				+ "�׳� �翡�� �־� �ּ���\r\n"
				+ "Ȱ¦ ���� �����\r\n"
				+ "��� ���� ������\r\n"
				+ "������ ���� �� �ϴ� ���\r\n"
				+ "������ ���� �����ٰ�\r\n"
				+ "����̷� ���ư� ����\r\n"
				+ "����ϴ� �� �ƹ���\r\n"
				+ "����ؿ� �� �ƹ���"));
		list.add(new Music("���� (Jessi)", "ZOOM", "https://cdnimg.melon.co.kr/cm2/album/images/109/18/269/10918269_20220413101153_500.jpg/melon/resize/120/quality/80/optimize", "Lights Camera Action\r\n"
				+ "\r\n"
				+ "I see you lookin at my P I C (I know)\r\n"
				+ "ũ�� ���� ���� �� �� ���ܺ� �� �������\r\n"
				+ "Zoom In, Zoom Out (OK)\r\n"
				+ "Zoom In, Zoom Out (OK)\r\n"
				+ "Zoom In, Zoom Out (OK)\r\n"
				+ "Baby Ȯ ���� Ȯ�� Ȯ���ϰ� Oww~\r\n"
				+ "\r\n"
				+ "I��m feelin like a million bucks yeah\r\n"
				+ "Must be the million bucks yeah\r\n"
				+ "���õ��� ���̳�\r\n"
				+ "Selfie ��Ĭ�ϸ� ���̳�\r\n"
				+ "Always talkin �� know you like that\r\n"
				+ "������ �� ������ ������\r\n"
				+ "Yea it��s like that, hey hey pretty lil thang\r\n"
				+ "Do ya thang, I��ll be right back\r\n"
				+ "\r\n"
				+ "(Woo) �츰 ��� ���� ��� ���� ���\r\n"
				+ "���� �׷� �� �� �˾� Aight\r\n"
				+ "(Woo) �츰 ��� ���ɹޱ� ���� ���\r\n"
				+ "���� �׷� �� �� �˾� Aight!\r\n"
				+ "\r\n"
				+ "Lights Camera Action Baby\r\n"
				+ "\r\n"
				+ "I see you lookin at my P I C (I know)\r\n"
				+ "ũ�� ���� ���� �� �� ���ܺ� �� �������\r\n"
				+ "Zoom In, Zoom Out (OK)\r\n"
				+ "Zoom In, Zoom Out (OK)\r\n"
				+ "Zoom In, Zoom Out (OK)\r\n"
				+ "Baby Ȯ ���� Ȯ�� Ȯ���ϰ� Oww~\r\n"
				+ "\r\n"
				+ "Do you like all my clothes and my bags?\r\n"
				+ "���� �԰� ���� ���� ���ε�?\r\n"
				+ "Why you like it when I��m sad or I��m mad?\r\n"
				+ "I don��t give uh, cuz I��ma bad\r\n"
				+ "���� ���� ���� Wishlist �׻� �� Pick\r\n"
				+ "����� �� �� ��� ���� ����ƽ?\r\n"
				+ "It��s funny how you always talking money\r\n"
				+ "But always playin a dummy\r\n"
				+ "Yous a bummy beggin yo mummy for money"));
		list.add(new Music("�̹���", "��ȣ��", "https://cdnimg.melon.co.kr/cm2/album/images/106/07/796/10607796_20210513201807_500.jpg/melon/resize/120/quality/80/optimize", "������ �������� ��������\r\n"
				+ "������ �� ���Ƽ��� �� �� ���� �յ�\r\n"
				+ "������ �󱼷� ȭ�� �´�\r\n"
				+ "ģ���� ��������\r\n"
				+ "�̹� �� �߰����� ��������\r\n"
				+ "������ �� �����ϳ� �ȱ⵵ ���絥\r\n"
				+ "���Ķ��� �̿� ���� ������\r\n"
				+ "ģ���� ���� �ɵ���\r\n"
				+ "�ǹ�ó�� ���� ���� ��\r\n"
				+ "������ ���׶�̵� ��ΰ�\r\n"
				+ "����� ������ ���� �� ���\r\n"
				+ "�װ� ���� ������ �Ƴ�\r\n"
				+ "������ Ǫ���� �� ����\r\n"
				+ "3�� �� ª�� �ð�\r\n"
				+ "����� ���� ����\r\n"
				+ "���� �� ��ȣ����\r\n"
				+ "�� �Ӹ����� �� �������\r\n"
				+ "���� ��������\r\n"
				+ "�������� �𸣰ھ�\r\n"
				+ "���� ������ ����� ���̾�\r\n"
				+ "������ �����ڸ� ����\r\n"
				+ "�����븦 �� ��� � ����\r\n"
				+ "�� ���Ҿ��� �� ����\r\n"
				+ "�׶� �Բ� �� ������\r\n"
				+ "�Ŵ� ģ���� �־�����\r\n"
				+ "�ǹ�ó�� ���� ���� ��\r\n"
				+ "������ ������� �� ������\r\n"
				+ "������ ���� ���߰� ������\r\n"
				+ "�� ���� ��¥�� ���̾�\r\n"
				+ "������ Ǫ���� �� ����\r\n"
				+ "3�� �� ª�� �ð�\r\n"
				+ "����� ���� ���� ���� �� ��ȣ����\r\n"
				+ "�� �Ӹ����� �� �������\r\n"
				+ "���� ��������\r\n"
				+ "�������� �𸣰ھ�\r\n"
				+ "���� ������ ����� ���̾�\r\n"
				+ "���������� ����̳�\r\n"
				+ "���� �翣 �ƹ��� ����\r\n"
				+ "��� ����� �̻� ĥ ����\r\n"
				+ "�� �־� �������� ��\r\n"
				+ "������ Ǫ���� �� ����\r\n"
				+ "3�� �� ª�� �ð�\r\n"
				+ "����� ���� ���� ���� �� ��ȣ����\r\n"
				+ "�� �Ӹ����� �� �������\r\n"
				+ "���� ��������\r\n"
				+ "�������� �𸣰ھ�\r\n"
				+ "���� ������ ����� ���̾�"));
		list.add(new Music("�漭����, ����ȣ", "������ �� �̸��� �θ���", "https://cdnimg.melon.co.kr/cm2/album/images/106/10/525/10610525_20210518143433_500.jpg/melon/resize/120/quality/80/optimize", "������ ������ ������ ��\r\n"
				+ "��� ���� �ٶ���\r\n"
				+ "�� ���� ��ġ��\r\n"
				+ "���� �ٴ� �Ѱ��� ����\r\n"
				+ "�Ƹ��ٿ� �ʿ� ��\r\n"
				+ "�׸��� �׷�����\r\n"
				+ "�� �� ���� �ճ�����\r\n"
				+ "�� ���� �����ִ� �Լ�\r\n"
				+ "�� ���� �� �޺���\r\n"
				+ "��������� �� ���� ���� �װ�\r\n"
				+ "������ �� �̸���\r\n"
				+ "�θ��� �� ������\r\n"
				+ "��Ƴ��� ������\r\n"
				+ "�� �ϳ� ���� �غ��\r\n"
				+ "���� ���� �� ������\r\n"
				+ "����� �ʴ� �ٴ� ����\r\n"
				+ "�ʿ� �Բ� �ȴ� �� ����\r\n"
				+ "�ϴ� �Ʒ� �ʿ� ��\r\n"
				+ "���� �� ��� ���� �ʿ���\r\n"
				+ "�� �൵ �� �Ʊ��\r\n"
				+ "�������� ����\r\n"
				+ "����� ���� �� �� ����\r\n"
				+ "�������� ���߰�\r\n"
				+ "�ϱ��� �ʴ� �ϸ�\r\n"
				+ "�Ͼ�� �ִ� �� �ƴ�\r\n"
				+ "5���� �Ǵ� ���� ó��\r\n"
				+ "�� ����� �Ǿ\r\n"
				+ "�δ� �ٶ��� ���� �Ǿ� ����\r\n"
				+ "������ �� �̸���\r\n"
				+ "�θ��� �� ������\r\n"
				+ "��Ƴ��� ������\r\n"
				+ "�� �ϳ� ���� �غ��\r\n"
				+ "���� ���� �� ������\r\n"
				+ "����� �ʴ� �ٴ� ����\r\n"
				+ "�ʿ� �Բ� �ȴ� �� ����"));
		list.add(new Music("�ӿ���", "���� �� ���� �״�", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "������ ������ ������ ��\r\n"
				+ "��� ���� �ٶ���\r\n"
				+ "�� ���� ��ġ��\r\n"
				+ "���� �ٴ� �Ѱ��� ����\r\n"
				+ "�Ƹ��ٿ� �ʿ� ��\r\n"
				+ "�׸��� �׷�����\r\n"
				+ "�� �� ���� �ճ�����\r\n"
				+ "�� ���� �����ִ� �Լ�\r\n"
				+ "�� ���� �� �޺���\r\n"
				+ "��������� �� ���� ���� �װ�\r\n"
				+ "������ �� �̸���\r\n"
				+ "�θ��� �� ������\r\n"
				+ "��Ƴ��� ������\r\n"
				+ "�� �ϳ� ���� �غ��\r\n"
				+ "���� ���� �� ������\r\n"
				+ "����� �ʴ� �ٴ� ����\r\n"
				+ "�ʿ� �Բ� �ȴ� �� ����\r\n"
				+ "�ϴ� �Ʒ� �ʿ� ��\r\n"
				+ "���� �� ��� ���� �ʿ���\r\n"
				+ "�� �൵ �� �Ʊ��\r\n"
				+ "�������� ����\r\n"
				+ "����� ���� �� �� ����\r\n"
				+ "�������� ���߰�\r\n"
				+ "�ϱ��� �ʴ� �ϸ�\r\n"
				+ "�Ͼ�� �ִ� �� �ƴ�\r\n"
				+ "5���� �Ǵ� ���� ó��\r\n"
				+ "�� ����� �Ǿ\r\n"
				+ "�δ� �ٶ��� ���� �Ǿ� ����\r\n"
				+ "������ �� �̸���\r\n"
				+ "�θ��� �� ������\r\n"
				+ "��Ƴ��� ������\r\n"
				+ "�� �ϳ� ���� �غ��"));
		list.add(new Music("�¿� (TAEYEON)", "INVU", "https://cdnimg.melon.co.kr/cm2/album/images/108/63/559/10863559_20220214160739_500.jpg/melon/resize/120/quality/80/optimize", "Falling in love\r\n"
				+ "�ʿ��� �� Option\r\n"
				+ "���ۺ��� �ٸ� �ʿ� ��\r\n"
				+ "������ Heart\r\n"
				+ "������ �� Mention\r\n"
				+ "�ͼ��ϰŵ�\r\n"
				+ "\r\n"
				+ "I think I lost my mind\r\n"
				+ "But It��s my kind of love\r\n"
				+ "�Ƴ��� �ʰ� ��\r\n"
				+ "��Ƴ���� �����ɾ�\r\n"
				+ "���� ��� ����\r\n"
				+ "��ģ ���� ����\r\n"
				+ "�־��� ������\r\n"
				+ "\r\n"
				+ "So I can��t love you\r\n"
				+ "Even though I do\r\n"
				+ "�о ����\r\n"
				+ "�� �ʸ� �� �̰�\r\n"
				+ "\r\n"
				+ "�� ������\r\n"
				+ "�� ��������\r\n"
				+ "�� ��¦�̴� ���̷���\r\n"
				+ "\r\n"
				+ "So I N V U\r\n"
				+ "I N V U\r\n"
				+ "I N V U\r\n"
				+ "\r\n"
				+ "����� ��\r\n"
				+ "��������� ��\r\n"
				+ "�� ���� �ǳ��� �ǇR��\r\n"
				+ "�� �ձ� �� ����\r\n"
				+ "�������� �� �� ��\r\n"
				+ "�� ����� �\r\n"
				+ "\r\n"
				+ "I guess I lost my mind\r\n"
				+ "Yeah It��s my kind of love\r\n"
				+ "�� ó���� ��ó��\r\n"
				+ "�������� �� ��ó�� ��\r\n"
				+ "�������� ����\r\n"
				+ "�ƹ��⵵ ����\r\n"
				+ "�ܶ� �������\r\n"
				+ "\r\n"
				+ "So I can��t love you\r\n"
				+ "Even though I do\r\n"
				+ "�о ����\r\n"
				+ "�� �ʸ� �� �̰�\r\n"
				+ "\r\n"
				+ "�� ������\r\n"
				+ "�� ��������\r\n"
				+ "�� ��¦�̴� ���̷���\r\n"
				+ "\r\n"
				+ "So I N V U\r\n"
				+ "I N V U\r\n"
				+ "I N V U\r\n"
				+ "\r\n"
				+ "���� �±�\r\n"
				+ "�μ��� ����\r\n"
				+ "�ڲ� �� ������\r\n"
				+ "���ĵ� �� ����\r\n"
				+ "So when you leave\r\n"
				+ "Please make it easy\r\n"
				+ "Cause I N V U\r\n"
				+ "\r\n"
				+ "I N V U\r\n"
				+ "I N V U\r\n"
				+ "I N V U\r\n"
				+ "\r\n"
				+ "I N V U"));
		list.add(new Music("IVE (���̺�)", "ELEVEN", "https://cdnimg.melon.co.kr/cm2/album/images/107/98/794/10798794_20211201113915_500.jpg/melon/resize/120/quality/80/optimize", "������ ���� ������\r\n"
				+ "��ǥ���ߴ� ����\r\n"
				+ "�� ���� ������ �־�\r\n"
				+ "�� ���� �����ڴ� odd\r\n"
				+ "\r\n"
				+ "�� �ȿ� �����ϰ� �Ǿ�� blue\r\n"
				+ "���� ���� ������ �� �������� true\r\n"
				+ "�� �Լ��� �������� ���� �� �̸�\r\n"
				+ "�� ������ �� ���� �̸� ��ä�ο���\r\n"
				+ "\r\n"
				+ "�� ���� �ٰ� �� �� ���� ���� heaven\r\n"
				+ "���� �߰� �� ���� �������� ��ŭ\r\n"
				+ "Oh my, oh my god\r\n"
				+ "�� ĭ �� ä��� �־�\r\n"
				+ "�� �� 1, 2, 3, 4, 5, 6, 7\r\n"
				+ "You make me feel like eleven\r\n"
				+ "\r\n"
				+ "������ �ʿ� ���� ����\r\n"
				+ "������ �鿩�ٺ���\r\n"
				+ "�Ϸ��� ���� ������\r\n"
				+ "�� ������� ��\r\n"
				+ "\r\n"
				+ "�׳� ���ο� �������� mood\r\n"
				+ "�� �� ���� �ݺ��ص� ��� ���� ��\r\n"
				+ "���� ���� �̷��� �� ������ �� ��\r\n"
				+ "�� ������ �� ���� �̸� ��ä�ο���\r\n"
				+ "\r\n"
				+ "�� ���� �ٰ� �� �� ���� ���� heaven\r\n"
				+ "���� �߰� �� ���� �������� ��ŭ\r\n"
				+ "Oh my, oh my god\r\n"
				+ "�� ĭ �� ä��� �־�\r\n"
				+ "�� �� 1, 2, 3, 4, 5, 6, 7\r\n"
				+ "You make me feel like eleven\r\n"
				+ "\r\n"
				+ "�� �տ� �ִ� �ʸ�\r\n"
				+ "�� ���� ��ģ ���� (�� ���� ��ģ ����)\r\n"
				+ "Aya, aya, aya (������ �ٶ��)\r\n"
				+ "�� �տ� �ִ� �ʸ�\r\n"
				+ "�� ���� ��ģ ����\r\n"
				+ "������ �ٶ��\r\n"
				+ "\r\n"
				+ "Don't say now\r\n"
				+ "���ѷ� ���� ��\r\n"
				+ "�� ������ ���� ��\r\n"
				+ "��ó ������ �� ���� �̸� ��ä�ο���\r\n"
				+ "\r\n"
				+ "�� ���� �ٰ� �� �� ���� ���� heaven\r\n"
				+ "���� �߰� �� ���� �������� ��ŭ\r\n"
				+ "Oh my, oh my god\r\n"
				+ "�� ĭ �� ä��� �־�\r\n"
				+ "�� �� 1, 2, 3, 4, 5, 6, 7\r\n"
				+ "You make me feel like eleven\r\n"
				+ "\r\n"
				+ "�� �տ� �ִ� �ʸ�\r\n"
				+ "�� ���� ��ģ ����\r\n"
				+ "Aya, aya, aya\r\n"
				+ "�� �տ� �ִ� �ʸ�\r\n"
				+ "�� ���� ��ģ ����\r\n"
				+ "����ϰ� �ưŵ�"));
		
		list.add(new Music("�ӿ���","A bientot", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "A bientot\r\n"
				+ "A bientot\r\n"
				+ "�� ���� ������ �������� �� ������\r\n"
				+ "���� �� ���� ȸ���� ���� ������\r\n"
				+ "�װ� ���� ���ڸ��� �ʹ� ũ�ϱ�\r\n"
				+ "�� �����Կ� ��� �ܿ� ��� ���ݾ�\r\n"
				+ "����� �����ϰ� �������� ������\r\n"
				+ "�ܿ� ���� �̷ﵵ ���ڸ��� �ڼ�����\r\n"
				+ "������ ���� ������ ������ �� �Ŀ�\r\n"
				+ "�ʶ�� �������� Ǯ���� �� �־���\r\n"
				+ "38�� �� ��ó�� ������\r\n"
				+ "�׳��� �µ��� ������ ���� ������\r\n"
				+ "��� �Ѹ����� ���� �̷��̶� ����\r\n"
				+ "����ó�� �� ������ �峪���\r\n"
				+ "�� �������� �ϳ����̾�\r\n"
				+ "�� �� ���� ���� �뷡��\r\n"
				+ "�����ϰ� �ν����ȳ�\r\n"
				+ "�� ���� ���� �⵵��\r\n"
				+ "�� ���� ���� �⵵��\r\n"
				+ "A bientot\r\n"
				+ "A bientot\r\n"
				+ "�λ��� �ʹ� �ܷο�\r\n"
				+ "�ʿ��� ��ȭ�� �ų׿�\r\n"
				+ "A bientot\r\n"
				+ "A bientot\r\n"
				+ "�λ��� �ʹ� �ܷο�\r\n"
				+ "�ʿ��� ��ȭ�� �ų׿�"));
		
		list.add(new Music("�ӿ���","����� ��¥", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "���� ���� ��� ���� �����ִ� �߾��\r\n"
				+ "���ٷ� ���� ����\r\n"
				+ "�״� ������� �Ʒ��ϰ� ������\r\n"
				+ "������ ������ �߼����� �ʾ�\r\n"
				+ "�״� �������Ƿ�\r\n"
				+ "�Ǿ ������ ����� ��\r\n"
				+ "�״� ���� ��������\r\n"
				+ "�� ��¥ ��¥ ��Ÿ��� ����ϰ� �����\r\n"
				+ "�� ���� ���� �״븸��\r\n"
				+ "�� ���� �״븸 ���� �־�\r\n"
				+ "�� ���� �״븦 ����մϴ�\r\n"
				+ "�������� ���� ���� �̿ϼ��� �׸� �ϳ�\r\n"
				+ "�׷� �� ���� ������\r\n"
				+ "��� �� �״밡 ���� ���� ������\r\n"
				+ "������ �ð��� �߼����� �ʾ�\r\n"
				+ "�״� �������Ƿ�\r\n"
				+ "�Ǿ ������ �����\r\n"
				+ "�״� ���� ��������\r\n"
				+ "�� ��¥ ��¥ ��Ÿ��� ����ϰ� �����\r\n"
				+ "�� ���� ���� �״븸��\r\n"
				+ "�� ���� �״븸 ���� �־�\r\n"
				+ "�� ���� �״븦 ����մϴ�"));
		
		list.add(new Music("(����)���̵�","MY BAG", "https://cdnimg.melon.co.kr/cm2/album/images/108/90/384/10890384_20220314111504_500.jpg/melon/resize/120/quality/80/optimize", "Red five diamonds in my bag\r\n"
				+ "If you wanna see it, dance to a beat like that\r\n"
				+ "My mama saw it and ��Oh my god dang��\r\n"
				+ "Ok I��ll show you what��s in my bag\r\n"
				+ "\r\n"
				+ "Red five diamonds in my bag\r\n"
				+ "If you wanna see it, dance to a beat like that\r\n"
				+ "My mama saw it and ��Oh my god dang��\r\n"
				+ "Ok I��ll show you what��s in my bag\r\n"
				+ "\r\n"
				+ "Uh oh I know you like it\r\n"
				+ "My voice�� ���� �� �� God dang\r\n"
				+ "Uh oh I just like it\r\n"
				+ "�»����� ���� Money ���� ����\r\n"
				+ "\r\n"
				+ "�ΰ��� ���� ������ ���� ������ ����\r\n"
				+ "Fantasy�� ���� ���� ���� �� ����\r\n"
				+ "�۷� ���� ���� �� ��� ���� ���� ��\r\n"
				+ "���� Vibe sugar high �� �� ���� ��� Die\r\n"
				+ "\r\n"
				+ "Rum-rum-rum Rumble �� Crumble\r\n"
				+ "�� Voice�� Drum���� No lose\r\n"
				+ "No no no lovely I��m Bumblebee\r\n"
				+ "�׳� �� �� �� �� �� One, two\r\n"
				+ "\r\n"
				+ "I never had �� a.k.a ��Giant dog��\r\n"
				+ "���� �ϰ� ���ٵ��� ���� �̰� ���� ��\r\n"
				+ "I value my love �׸� �ε�� ��\r\n"
				+ "�Ӹ� �� ��û�̵���� ��� ���� ���� �޶� Ye you know\r\n"
				+ ""));
		list.add(new Music("�ӿ���","����� ��¥", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "���� ���� ��� ���� �����ִ� �߾��\r\n"
				+ "���ٷ� ���� ����\r\n"
				+ "�״� ������� �Ʒ��ϰ� ������\r\n"
				+ "������ ������ �߼����� �ʾ�\r\n"
				+ "�״� �������Ƿ�\r\n"
				+ "�Ǿ ������ ����� ��\r\n"
				+ "�״� ���� ��������\r\n"
				+ "�� ��¥ ��¥ ��Ÿ��� ����ϰ� �����\r\n"
				+ "�� ���� ���� �״븸��\r\n"
				+ "�� ���� �״븸 ���� �־�\r\n"
				+ "�� ���� �״븦 ����մϴ�\r\n"
				+ "�������� ���� ���� �̿ϼ��� �׸� �ϳ�\r\n"
				+ "�׷� �� ���� ������\r\n"
				+ "��� �� �״밡 ���� ���� ������\r\n"
				+ "������ �ð��� �߼����� �ʾ�\r\n"
				+ "�״� �������Ƿ�\r\n"
				+ "�Ǿ ������ �����\r\n"
				+ "�״� ���� ��������\r\n"
				+ "�� ��¥ ��¥ ��Ÿ��� ����ϰ� �����\r\n"
				+ "�� ���� ���� �״븸��\r\n"
				+ "�� ���� �״븸 ���� �־�\r\n"
				+ "�� ���� �״븦 ����մϴ�"));
		list.add(new Music("MSG���ʺ�(M.O.M)","��� ������", "https://cdnimg.melon.co.kr/cm2/album/images/108/80/544/10880544_20220225141002_500.jpg/melon/resize/120/quality/80/optimize", "�츮 �Բ� ��� �� �뷤 ��� ������\r\n"
				+ "��� ���� ��� �� ������ �ұ�\r\n"
				+ "���� Ȥ�ö� �� ���� ���� ������\r\n"
				+ "�� �� �� ��Ҹ��� ��� ������\r\n"
				+ "���ϵ� ���� �뷧�� ���� �̾���\r\n"
				+ "�̾��ص� �ε� �� �� ������� ��\r\n"
				+ "��ȸ�� �̷õ� ���� ô ��������\r\n"
				+ "�̰� �� ������ �� �� �˾����� ��\r\n"
				+ "�츮 �Բ� ��� �� �뷤 ��� ������\r\n"
				+ "��� ���� ��� �� ������ �ұ�\r\n"
				+ "���� Ȥ�ö� �� ���� ���� ������\r\n"
				+ "���� �� ��Ҹ��� ��� ������\r\n"
				+ "������ �� �������� �� ���� �� ���� ����\r\n"
				+ "�� ��° ���� favorite one\r\n"
				+ "You the only one yeah\r\n"
				+ "Yes I know ������ �޶��� �� ������\r\n"
				+ "�̰� �� ������ �� �� �˾����� ��\r\n"
				+ "�츮 �Բ� ��� �� �뷤 ��� ������\r\n"
				+ "��� ���� ��� �� ������ �ұ�\r\n"
				+ "���� Ȥ�ö� �� ���� ���� ������\r\n"
				+ "�� �� �� ��Ҹ��� ��� ������"));
		list.add(new Music("�ӿ���","��������", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "������ ���� ���� �ϴ���\r\n"
				+ "�������� �� ���� �����Դϴ�\r\n"
				+ "���� ������ �״� ������\r\n"
				+ "�������� �̸��� �ҷ����ϴ�\r\n"
				+ "���� ���� ���� �� ���� ��ø��\r\n"
				+ "�״밡 �ʹ��� ����\r\n"
				+ "���� �׸��� �� ���\r\n"
				+ "������ �־� ������\r\n"
				+ "�Ͼ� ���̿� ���� ���� ��\r\n"
				+ "���� �״� �� ��� ����Դϴ�\r\n"
				+ "�ܷ��� ���� â�� ����\r\n"
				+ "�ٶ� �Ҹ� ������ �ð��Դϴ�\r\n"
				+ "��� ����� �ʸ� �¿��\r\n"
				+ "�������� �״븦 �ҷ����ϴ�\r\n"
				+ "���� ���� ���� �� ���� ������\r\n"
				+ "�״밡 �ʹ��� ����\r\n"
				+ "���� �׸��� �� ���\r\n"
				+ "�ٶ� ���ϴÿ���\r\n"
				+ "�ƽ����� �� ���� �� �ϳ�\r\n"
				+ "�ܷ��� Ȧ�� ���� �����Դϴ�"));
		list.add(new Music("��ȣ", "���� �ƴ϶�", "https://cdnimg.melon.co.kr/cm2/album/images/108/97/407/10897407_20220323150744_500.jpg/melon/resize/120/quality/80/optimize", "����̾��� ���� ���� �� �Ϸ翡\r\n"
				+ "���� ���� ���� ���\r\n"
				+ "������ ���� �� �Ʋ� �ִ� �ʸ�\r\n"
				+ "�׶� �� ��������\r\n"
				+ "�ູ�̾��� �ٽô� ���� �� ����\r\n"
				+ "��ó��� �ູ�߾���\r\n"
				+ "�ٸ� ��� �翡 �ִ� ��\r\n"
				+ "������ �� �� ������\r\n"
				+ "���� �ʸ� ������� �� �� ����\r\n"
				+ "���� �ƴ϶�\r\n"
				+ "���νð� ����޾��� �ʶ�\r\n"
				+ "�� ������ �ð��� ���� �Բ��� �༭\r\n"
				+ "������\r\n"
				+ "���ڰ� �Ƹ��ٿ��� ���� �׳���\r\n"
				+ "�Բ��ߴ� �� ��� ������ �ູ�߾�\r\n"
				+ "�� ���ο��� ������ �ٲ� �� ����\r\n"
				+ "�츮�� �ູ�߾���\r\n"
				+ "�ٸ� ������\r\n"
				+ "������ �� ���� ��� ������\r\n"
				+ "���� ���� �ذ� �ູ�ϰ� ���\r\n"
				+ "���� �ƴ϶�\r\n"
				+ "���νð� ����޾��� �ʶ�\r\n"
				+ "�� ������ �ð��� ���� �Բ��� �༭\r\n"
				+ "������"));
		list.add(new Music("The Kid LAROI, Justin Bieber", "STAY", "https://cdnimg.melon.co.kr/cm2/album/images/106/46/395/10646395_20210707141710_500.jpg/melon/resize/120/quality/80/optimize", "I do the same thing I told you\r\n"
				+ "that I never would\r\n"
				+ "I told you I'd change\r\n"
				+ "even when I knew I never could\r\n"
				+ "I know that I can't find\r\n"
				+ "nobody else\r\n"
				+ "as good as you\r\n"
				+ "I need you to stay\r\n"
				+ "need you to stay hey Oh\r\n"
				+ "I get drunk wake up\r\n"
				+ "I'm wasted still\r\n"
				+ "I realize the time\r\n"
				+ "that I wasted here\r\n"
				+ "I feel like you can't\r\n"
				+ "feel the way I feel\r\n"
				+ "Oh I'll be fucked up\r\n"
				+ "if you can't be right here\r\n"
				+ "Oh ooh-woah\r\n"
				+ "Oh ooh-woah ooh-woah\r\n"
				+ "Oh ooh-woah\r\n"
				+ "Oh ooh-woah ooh-woah\r\n"
				+ "Oh ooh-woah\r\n"
				+ "Oh ooh-woah ooh-woah\r\n"
				+ "Oh I'll be fucked up\r\n"
				+ "if you can't be right here\r\n"
				+ "I do the same thing I told you\r\n"
				+ "that I never would\r\n"
				+ "I told you I'd change\r\n"
				+ "even when I knew I never could\r\n"
				+ "I know that I can't find\r\n"
				+ "nobody else\r\n"
				+ "as good as you\r\n"
				+ "I need you to stay\r\n"
				+ "need you to stay hey\r\n"
				+ "I do the same thing I told you\r\n"
				+ "that I never would\r\n"
				+ "I told you I'd change\r\n"
				+ "even when I knew I never could\r\n"
				+ "I know that I can't find\r\n"
				+ "nobody else"));
		list.add(new Music("Charlie Puth","That's Hilarious", "https://cdnimg.melon.co.kr/cm2/album/images/108/44/485/10844485_20220407163235_500.jpg/melon/resize/120/quality/80/optimize", "Look how all tables,\r\n"
				+ "Look how all the tables have turned,\r\n"
				+ "Guess you��re finally realizing how bad you messed it up\r\n"
				+ "Girl you��re only making,\r\n"
				+ "Girl you��re only making it worse,\r\n"
				+ "When you call like you always do when you want someone\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Pre-Chorus:\r\n"
				+ "You took away a year,\r\n"
				+ "of my fucking life and I can��t get it back no more\r\n"
				+ "So when I see those tears,\r\n"
				+ "Coming out your eyes I hope it��s me there for\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Chorus:\r\n"
				+ "You didn��t love when you had me\r\n"
				+ "But now you need me so badly\r\n"
				+ "You can��t be serious\r\n"
				+ "That��s hilarious\r\n"
				+ "Thinking I would still want you\r\n"
				+ "After the things you put me through\r\n"
				+ "Yea You��re delirious\r\n"
				+ "That��s hilarious"));
		list.add(new Music("���̽�(Kassy)","���� �� ������� �ʹ� �ƽ���", "https://cdnimg.melon.co.kr/cm2/album/images/109/60/568/10960568_20220518153132_500.jpg/melon/resize/120/quality/80/optimize", "��¼�� �ʵ� ���� ���� �� �ܱ�\r\n"
				+ "���� ���� ���� ���ߴ� �Ϸ�\r\n"
				+ "���� �� ������� �ʹ� �ƽ���\r\n"
				+ "�� ���� ����ϳ� ��\r\n"
				+ "������ ������ ���� ��\r\n"
				+ "�� ���� �����̰� ��\r\n"
				+ "��ȭ �ӿ����� ���� �ϵ���\r\n"
				+ "���� �� �ϻ��� ����\r\n"
				+ "��¼�� �ʵ� ���� ���� �� �ܱ�\r\n"
				+ "���� ���� ���� ���ߴ� �Ϸ�\r\n"
				+ "���� �� ������� �ʹ� �ƽ���\r\n"
				+ "�� ���� ����ϳ� ��\r\n"
				+ "���� �ʿ��� ����ϰھ�\r\n"
				+ "���ؼ� �ϴ� ���� �Ƴ�\r\n"
				+ "���ƿ� ������ �ž�\r\n"
				+ "�Ϸ� ���� �ƹ��͵� �� �ص�\r\n"
				+ "�ʶ� �ִ� �� �� ����\r\n"
				+ "�޺��� �ϴ� �Ʒ� �츮�� ���߰�\r\n"
				+ "�� ������ ��� ��� �� ����\r\n"
				+ "���� �� ������� �ʹ� �ƽ���\r\n"
				+ "�� ���� ����ϳ� ��\r\n"
				+ "�װ� ��ư��� ������\r\n"
				+ "�� ��� ������ ���� ���� ��\r\n"
				+ "���� �� �λ��� ��Ÿ���༭\r\n"
				+ "�̷��� �� �Ⱦ��༭\r\n"
				+ "���� �ʿ��� ����ϰھ�"));
		list.add(new Music("�ӿ���","�����ڸ�", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "�״� ����� ������ ���ڴ�\r\n"
				+ "�ƹ��͵� �ʿ� �����\r\n"
				+ "����� ǰ�� �Ȱ� ���� �;��\r\n"
				+ "�� ����� �����ڸ�\r\n"
				+ "�ƹ��͵� �ٶ��� �ʾƿ�\r\n"
				+ "��Ÿ� ������ ��\r\n"
				+ "�� �� ���� �ʰ� ����ҷ���\r\n"
				+ "���� �ʿ� ���� �鵵 �ʿ� ����\r\n"
				+ "��Ÿ� ������ ��\r\n"
				+ "�״� ����� ������ ���ڴ�\r\n"
				+ "�ƹ��͵� �ʿ� �����\r\n"
				+ "����� ǰ�� �Ȱ� ���� �;��\r\n"
				+ "�� ����� �����ڸ�\r\n"
				+ "�ƹ��͵� �ٶ��� �ʾƿ�\r\n"
				+ "��Ÿ� ������ ��\r\n"
				+ "�� �� ���� �ʰ� ����ҷ���\r\n"
				+ "���� �ʿ� ���� �鵵 �ʿ� ����\r\n"
				+ "��Ÿ� ������ ��\r\n"
				+ "�ƹ��͵� �ٶ��� �ʾƿ�\r\n"
				+ "��Ÿ� ������ ��\r\n"
				+ "�� �� ���� �ʰ� ����ҷ���\r\n"
				+ "���� �ʿ� ���� �鵵 �ʿ� ����\r\n"
				+ "��Ÿ� ������ ��\r\n"
				+ "��Ÿ� ������ ��"));
		list.add(new Music("�ӿ���","����ؿ� �״븦", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "�ʹ��� ���� ���\r\n"
				+ "�ʹ��� ������ ���\r\n"
				+ "�� ���� �ؾ �� ����\r\n"
				+ "�� �����ӿ� �� ���\r\n"
				+ "�� �״� ������ �ص�\r\n"
				+ "������ ��Ŭ������\r\n"
				+ "�׷� ��� �� �翡 �־�\r\n"
				+ "���� �ູ�� ���\r\n"
				+ "�״�� ������ ���\r\n"
				+ "�״�� ������ �ູ\r\n"
				+ "���� ���� ������\r\n"
				+ "����� ������ ���\r\n"
				+ "����ؿ� �״븦\r\n"
				+ "����ؿ� �״븦\r\n"
				+ "�� ���� ���� ������\r\n"
				+ "����� �� ���\r\n"
				+ "����ؿ� �״븦\r\n"
				+ "����ؿ� �״븦\r\n"
				+ "�� ���� ���� ������\r\n"
				+ "����� �����\r\n"
				+ "�״�� ������ ���\r\n"
				+ "�״�� ������ �ູ\r\n"
				+ "���� ���� ������\r\n"
				+ "����� ������ ���"));
		list.add(new Music("����ƾ","Dar+ing", "https://cdnimg.melon.co.kr/cm2/album/images/109/22/231/10922231_20220527120653_500.jpg/melon/resize/120/quality/80/optimize", "You know without you I��m so lonely\r\n"
				+ "When you��re not here 911 calling\r\n"
				+ "Into your heat again I��m diving\r\n"
				+ "Darling you Darling you baby\r\n"
				+ "\r\n"
				+ "Fighting round in circles where is the way out\r\n"
				+ "��Cause I know that our love was hotter than the sun\r\n"
				+ "Yeah the taste of this tequila I��m drinking now\r\n"
				+ "Isn��t bitter than my heart\r\n"
				+ "\r\n"
				+ "(If you know this)\r\n"
				+ "I want to know our problem blood type or DNA\r\n"
				+ "Friends see my feed and worry, do you babe? Yeah\r\n"
				+ "Been waiting for your call every night\r\n"
				+ "But I can��t wait no more\r\n"
				+ "Dialing you-u-u, sorry darling you\r\n"
				+ "\r\n"
				+ "You know without you I��m so lonely\r\n"
				+ "When you��re not here 911 calling\r\n"
				+ "Into your heat again I��m diving\r\n"
				+ "Darling you Darling you baby\r\n"
				+ "\r\n"
				+ "You know without you I��m so lonely\r\n"
				+ "If you won��t be here 911 calling\r\n"
				+ "Falling to you I��m always diving\r\n"
				+ "Darling you Darling you baby\r\n"
				+ "\r\n"
				+ "Darling with me under the sun\r\n"
				+ "I know that you��re my one"));
		list.add(new Music("��ź�ҳ��","Dynamite", "https://cdnimg.melon.co.kr/cm2/album/images/104/79/150/10479150_20200918102847_500.jpg/melon/resize/120/quality/80/optimize", "Cos ah ah\r\n"
				+ "I��m in the stars tonight\r\n"
				+ "So watch me bring the fire\r\n"
				+ "and set the night alight\r\n"
				+ "Shoes on get up in the morn\r\n"
				+ "Cup of milk let��s rock and roll\r\n"
				+ "King Kong kick the drum\r\n"
				+ "rolling on like a rolling stone\r\n"
				+ "Sing song when I��m walking home\r\n"
				+ "Jump up to the top LeBron\r\n"
				+ "Ding dong call me on my phone\r\n"
				+ "Ice tea and a game of ping pong\r\n"
				+ "This is getting heavy\r\n"
				+ "Can you hear the bass boom\r\n"
				+ "I��m ready\r\n"
				+ "Life is sweet as honey\r\n"
				+ "Yeah this beat cha ching\r\n"
				+ "like money\r\n"
				+ "Disco overload I��m into\r\n"
				+ "that I��m good to go\r\n"
				+ "I'm diamond you know I glow up\r\n"
				+ "Hey so let��s go\r\n"
				+ "Cos ah ah\r\n"
				+ "I��m in the stars tonight\r\n"
				+ "So watch me bring the fire\r\n"
				+ "and set the night alight\r\n"
				+ "Shining through the city\r\n"
				+ "with a little funk and soul\r\n"
				+ "So I��mma light it up\r\n"
				+ "like dynamite woah\r\n"
				+ "Bring a friend join the crowd\r\n"
				+ "Whoever wanna come along\r\n"
				+ "Word up talk the talk\r\n"
				+ "just move like we off the wall\r\n"
				+ "Day or night the sky��s alight\r\n"
				+ "So we dance to the break of dawn\r\n"
				+ "Ladies and gentlemen\r\n"
				+ "I got the medicine\r\n"
				+ "so you should keep ya\r\n"
				+ "eyes on the ball huh\r\n"
				+ "This is getting heavy\r\n"
				+ "Can you hear the bass boom"));
		list.add(new Music("�¿� (TAEYEON)","Weekend", "https://cdnimg.melon.co.kr/cm2/album/images/106/45/654/10645654_20210706155154_500.jpg/melon/resize/120/quality/80/optimize", "���� ����� �ٴ�\r\n"
				+ "ȥ�ڸ��� ��ȭ��\r\n"
				+ "�׳� �̲����� ��� �ص� �������ϱ�\r\n"
				+ "Every morning �︰\r\n"
				+ "Beep beep beep beep �Ҹ�\r\n"
				+ "�Ϳ� ������ �ɵ���\r\n"
				+ "���� �����ϴ� ����� ���� �Ͼ\r\n"
				+ "Cheese cake �� ��\r\n"
				+ "������ �Ѱ���\r\n"
				+ "���� Ŀ�� �� ��\r\n"
				+ "���̽��� �ҷ� ���� �����Ӱ�\r\n"
				+ "���� �ð� ����\r\n"
				+ "���� �ð��� ���ν�\r\n"
				+ "�׷��� ���� ������\r\n"
				+ "�׸��� ��ǰ �� ��\r\n"
				+ "�Ѳ� �������� �Ѱ�\r\n"
				+ "������ ���� �� �ұ�\r\n"
				+ "â�� �ʸ� ������ �ü��� ���� �� ����\r\n"
				+ "������� �޻� �� ���� �ε��\r\n"
				+ "���� �����ϴ� �̱׷��� �ٶ� Ÿ��\r\n"
				+ "�������� When the weekend comes\r\n"
				+ "I can do whatever I want\r\n"
				+ "�ٶ� ���� ����� cloud\r\n"
				+ "�� �����Ӱ� we can go\r\n"
				+ "���� ����� �ٴ�\r\n"
				+ "ȥ�ڸ��� ��ȭ��\r\n"
				+ "�׳� �̲����� ��� �ص� �������ϱ�\r\n"
				+ "��½ �������� drive\r\n"
				+ "�ѹ� �ɾ ����"));
		list.add(new Music("aespa","Next Level", "https://cdnimg.melon.co.kr/cm2/album/images/106/09/232/10609232_20210517155130_500.jpg/melon/resize/120/quality/80/optimize", "I��m on the Next Level Yeah\r\n"
				+ "������ ���� ����\r\n"
				+ "�� ���� ���� ����\r\n"
				+ "����� ���� ����\r\n"
				+ "���߷� �ɾ\r\n"
				+ "�˾� �� Home ground\r\n"
				+ "������ �¼���\r\n"
				+ "������ ������ ������\r\n"
				+ "\r\n"
				+ "��� ���� Black out\r\n"
				+ "��Ȥ�� ��� ����\r\n"
				+ "(Too hot too hot)\r\n"
				+ "������ ���� ����\r\n"
				+ "�� ���� ���� ����\r\n"
				+ "\r\n"
				+ "I��m on the Next Level\r\n"
				+ "�� �ʸ��� ���� ����\r\n"
				+ "Next Level\r\n"
				+ "�� �ᱹ�� ���� �μ�\r\n"
				+ "Next Level\r\n"
				+ "KOSMO�� ���� ������\r\n"
				+ "Next Level\r\n"
				+ "������ ������ ������\r\n"
				+ "\r\n"
				+ "La la la la la la\r\n"
				+ "La la la la la la\r\n"
				+ "La la la la la la\r\n"
				+ "La la la la la"));
		list.add(new Music("��ź�ҳ��","Butter", "https://cdnimg.melon.co.kr/cm2/album/images/106/12/483/10612483_20210521111412_500.jpg/melon/resize/120/quality/80/optimize", "Smooth like butter\r\n"
				+ "Like a criminal undercover\r\n"
				+ "Gon�� pop like trouble\r\n"
				+ "Breakin�� into your heart like that\r\n"
				+ "\r\n"
				+ "Cool shade stunner\r\n"
				+ "Yeah I owe it all to my mother\r\n"
				+ "Hot like summer\r\n"
				+ "Yeah I��m makin�� you sweat like that\r\n"
				+ "\r\n"
				+ "Break it down\r\n"
				+ "\r\n"
				+ "Oh when I look in the mirror\r\n"
				+ "I��ll melt your heart into 2\r\n"
				+ "I got that superstar glow so\r\n"
				+ "Do the boogie like\r\n"
				+ "\r\n"
				+ "Side step right left to my beat (heartbeat)\r\n"
				+ "High like the moon rock with me baby\r\n"
				+ "Know that I got that heat\r\n"
				+ "Let me show you ��cause talk is cheap\r\n"
				+ "Side step right left to my beat (heartbeat)\r\n"
				+ "Get it, let it roll\r\n"
				+ "\r\n"
				+ "Smooth like butter\r\n"
				+ "Pull you in like no other\r\n"
				+ "Don��t need no Usher\r\n"
				+ "To remind me you got it bad\r\n"
				+ "\r\n"
				+ "Ain��t no other\r\n"
				+ "That can sweep you up like a robber\r\n"
				+ "Straight up, I got ya\r\n"
				+ "Makin�� you fall like that\r\n"
				+ "\r\n"
				+ "Break it down\r\n"
				+ ""));
		list.add(new Music("�ֽ�ũ (Joosiq)","�ʸ� ������", "https://cdnimg.melon.co.kr/cm2/album/images/107/16/399/10716399_20210916173429_500.jpg/melon/resize/120/quality/80/optimize", "�ʸ� ����ְ� �;���\r\n"
				+ "�� �뷤 ���� ��\r\n"
				+ "�Ƹ� �ϰ� ���� ���� �����Ҳ���\r\n"
				+ "���� ���� �ϰ� ���\r\n"
				+ "�� ȥ�� �ҷ���\r\n"
				+ "Ȥ�� ��� �Ǹ� �װ� �� �����\r\n"
				+ "�� �뷤 ���� ��\r\n"
				+ "�� �ʸ� ������\r\n"
				+ "��� ȥ�� ������ ǥ��\r\n"
				+ "���� �����Ÿ��� ����\r\n"
				+ "�׻� ���Ÿ��� ���� �ҷ���\r\n"
				+ "���� ���� �ų��ִ� �ʿ���\r\n"
				+ "�ҷ��ְ� �ʹ� �뷡��\r\n"
				+ "�� ������ �ܿ� �ϼ�������\r\n"
				+ "�� �뷣 �� ����Ѵٴ� �� ��Ⱑ\r\n"
				+ "�ܶ� ����� �ϴ� �뷣��\r\n"
				+ "�ʸ� ����ְ� �;���\r\n"
				+ "�� �뷤 ���� ��\r\n"
				+ "�Ƹ� �ϰ� ���� ���� �����Ҳ���\r\n"
				+ "���� ���� �ϰ� ���\r\n"
				+ "�� ȥ�� �ҷ���\r\n"
				+ "Ȥ�� ��� �Ǹ� �װ� �� �����\r\n"
				+ "�ϰ� ���� �����ߴ� ī�信\r\n"
				+ "�� �뷡�� ���� ������\r\n"
				+ "�� ģ���� ���� �θ� ������\r\n"
				+ "�� �뷤 ���������� ��� �ҷ���\r\n"
				+ "���� �ʿ��Է� �� ��� ���ž�\r\n"
				+ "�ʸ� ����ְ� �;���"));
		list.add(new Music("YENA (�ֿ���)","SMILEY (Feat. BIBI)", "https://cdnimg.melon.co.kr/cm2/album/images/108/42/611/10842611_20220117110002_500.jpg/melon/resize/120/quality/80/optimize", "���� �� ���� ��\r\n"
				+ "����̰���\r\n"
				+ "���� �� ���� ��\r\n"
				+ "�̱�� �Ŷ��\r\n"
				+ "You are so cute\r\n"
				+ "You are so dumb\r\n"
				+ "�װ� �ϴ� ����\r\n"
				+ "���õ��� ��� �Ⱦ�\r\n"
				+ "�ϴ��� �� �� �Ĵٺ���\r\n"
				+ "���� �� ����\r\n"
				+ "���� �� ���\r\n"
				+ "�װ� ��� �����ٰ�\r\n"
				+ "And I say Hey\r\n"
				+ "I��m gonna make it\r\n"
				+ "Smile Smile Smile away\r\n"
				+ "���ڰ� ���� �Ѱܹ�����\r\n"
				+ "Just Smile away\r\n"
				+ "Just Smile away\r\n"
				+ "���� ���� �ܷο� �ذ�\r\n"
				+ "I say hey\r\n"
				+ "I never wanna Cry Cry Cry all day\r\n"
				+ "���ڱ� ������ ������ ��\r\n"
				+ "Just Smile away\r\n"
				+ "Just Smile away\r\n"
				+ "�ȳ��̶� ���ҷ�\r\n"
				+ "With my Smiley face\r\n"
				+ "����� �� ����\r\n"
				+ "�� �Բ����� Chillin��\r\n"
				+ "�������� ��Ƴ��� �� ����\r\n"
				+ "�Ϳ��� ���ڸ� �嶯�̳� �ٵ�\r\n"
				+ "�� ���� �����ϱ� ����̰� ����"));
		list.add(new Music("���̽� (Kassy)","������ �����", "https://cdnimg.melon.co.kr/cm2/album/images/108/57/681/10857681_20220204162442_500.jpg/melon/resize/120/quality/80/optimize", "���� ����� ���� ��\r\n"
				+ "���� ���� �� ���� ��\r\n"
				+ "����Ѵ� ������ �ʾƵ� �˾�\r\n"
				+ "�� ������ ���� �濡\r\n"
				+ "�� �԰��� �� ȯ�� �̼Ҹ���\r\n"
				+ "�帣�� �־�\r\n"
				+ "����� �ʸ� �����\r\n"
				+ "���� ������ �����\r\n"
				+ "���� ���ϴ��� ������\r\n"
				+ "�������� �װ� �� ������\r\n"
				+ "�󸶳� ���� �󸶳� �ʸ� ����ϴ���\r\n"
				+ "�� ��� �� �ʿ��� �ٰ�\r\n"
				+ "�ӻ��ϰ� ���� �� ��\r\n"
				+ "���� ���� ������ ��\r\n"
				+ "������ �� ���� ���� ��� �ʾ�\r\n"
				+ "���� ���ƿ��� �濡\r\n"
				+ "�� �Ӱ��� �� ���� ��������\r\n"
				+ "�帣�� �־�\r\n"
				+ "����� �ʸ� �����\r\n"
				+ "���� ������ �����\r\n"
				+ "���� ���ϴ��� ������\r\n"
				+ "�������� �װ� �� ������\r\n"
				+ "�󸶳� ���� �󸶳� �ʸ� ����ϴ���\r\n"
				+ "�� ��� �� �ʿ��� �ٰ�\r\n"
				+ "���� ���� ���� ������ ��\r\n"
				+ "�̿� ���� ���� ����� ���\r\n"
				+ "�� �ʳ� ���� �� �ʳ�\r\n"
				+ "�츮 �� ���� �׳���\r\n"
				+ "���� ����� �� �ʿ��� ���ٰ�"));
		list.add(new Music("���ð�","���� ��� ����", "https://cdnimg.melon.co.kr/cm/album/images/022/32/505/2232505_500.jpg/melon/resize/120/quality/80/optimize", "������ ���� �Ѵ���\r\n"
				+ "�ʸ� �˾ƺ��� ��\r\n"
				+ "��� �� �и� �޶����� �־���\r\n"
				+ "�� ������ �� �˱� ���� �ķ� ������\r\n"
				+ "�ϰ� �� ���� ������ �ٶ��� �Ҿ��\r\n"
				+ "�ϰ� ������ ���ν� �޻��� ����\r\n"
				+ "�ű� �־��༭ �װ� �ʶ�\r\n"
				+ "���� �� ����� ������ ����־\r\n"
				+ "���� ���ݾ� ���� ��ƴ���� �ູ��\r\n"
				+ "�ʸ� ���� �ð��� �帣�� ����\r\n"
				+ "�������� �ʸ� �鿩�� ���� ��\r\n"
				+ "�װ� ����� �ƹ��͵� �� �� ���\r\n"
				+ "���� ��� ���� �װ�\r\n"
				+ "�������� ���ڴ�\r\n"
				+ "������ �ص� ������ ���ö�\r\n"
				+ "���� ���� �ʷ�\r\n"
				+ "���� ������ ���� ��ó�� �Ƶ��� ��\r\n"
				+ "�� ���� ���� �� ���� ���ƿ� ����\r\n"
				+ "�� ������ ��\r\n"
				+ "�ű� �־��༭ �װ� �ʶ�"));
		list.add(new Music("�ֽ�ũ (Joosiq)","�ƹ����� ��", "https://cdnimg.melon.co.kr/cm2/album/images/109/03/658/10903658_20220329185034_500.jpg/melon/resize/120/quality/80/optimize", "�ƹ����� �ʰ� �� �Ϸ簡 ��\r\n"
				+ "������ �뿡 ����\r\n"
				+ "�װ� ���ٴ� �� �ͼ����� ����\r\n"
				+ "���������� �� yeah\r\n"
				+ "������ �� ���� �� �ǹ� ���ٰ�\r\n"
				+ "�ǵ��� �� ���� �츮������\r\n"
				+ "�װ� �����ߴ� �� �뷤 �쿬��\r\n"
				+ "��� �ƾ� �ƹ����� ��\r\n"
				+ "Baby I Need You\r\n"
				+ "�� �ʾ�������\r\n"
				+ "�ٽ� �ϰ� �;�\r\n"
				+ "������ I Need you\r\n"
				+ "Need You\r\n"
				+ "�� ��ư�����\r\n"
				+ "�� ���� �ȵ� ��\r\n"
				+ "�ʵ� ���ݾ�\r\n"
				+ "Baby I need you now\r\n"
				+ "Baby I need you now\r\n"
				+ "Baby I need you now\r\n"
				+ "�� ���� �뷡�� �ʸ� �ҷ�����\r\n"
				+ "�ʵ� ���������\r\n"
				+ "������ �ñ���\r\n"
				+ "���� ���� ����\r\n"
				+ "���� ������ �\r\n"
				+ "������ �� ���� �� �ǹ� ���ٰ�\r\n"
				+ "�ǵ��� �� ���� �츮������\r\n"
				+ "�װ� �����ߴ� �� �뷤 �쿬��\r\n"
				+ "�ҷ� �þ� �ƹ����� ��\r\n"
				+ "Baby I Need You\r\n"
				+ "�� �ʾ�������\r\n"
				+ "�ٽ� �ϰ� �;�"));
		list.add(new Music("������","���", "https://cdnimg.melon.co.kr/cm2/album/images/108/27/816/10827816_20211229143632_500.jpg/melon/resize/120/quality/80/optimize", "���� �Ѷ��� ������ ���� ���\r\n"
				+ "���� �� ���� ���ΰ��� �� ��\r\n"
				+ "�ɼ����� ���� �ϳ��ϳ�����\r\n"
				+ "��� �� ���� �Ǿ��\r\n"
				+ "\r\n"
				+ "�ø��ȴ�� �Ҽ� ������\r\n"
				+ "���� ����� ���� �Ĵ�\r\n"
				+ "���� ��û�Ÿ��� ����\r\n"
				+ "�ֿ����� ����\r\n"
				+ "\r\n"
				+ "�ٽ� ������ ����� �� ������\r\n"
				+ "���ڴٴ� �� ���� �� ������\r\n"
				+ "�Ϸ� �� �Ϸ縸 ��ȸ�� �´ٸ�\r\n"
				+ "�������� ���� ������\r\n"
				+ "\r\n"
				+ "�������ϰ� �ް��ϰ�\r\n"
				+ "������ �ٲ�� �������\r\n"
				+ "������ ���� ��Ʈ�忡\r\n"
				+ "ȥ�� ������ ����"));
		
		return list;
	}
}
